export const STAT_KEYS = Object.freeze(["strength", "dexterity", "intellect", "insight", "presence"]);

const ability = (id, name, description, config = {}) => Object.freeze({
  id,
  name,
  description,
  range: 1,
  radius: 0,
  cooldown: 0,
  damage: null,
  heal: null,
  stat: "strength",
  target: "enemy",
  ...config,
});

export const HEROES = Object.freeze([
  {
    id: "brom-stoneguard",
    name: "Brom Stoneguard",
    className: "Vanguard",
    role: "Front-line defender",
    tagline: "Stand behind me. Preferably far behind me.",
    stats: { strength: 4, dexterity: 1, intellect: 1, insight: 2, presence: 2 },
    maxHp: 42, defense: 15, move: 4, initiative: 1,
    palette: ["#d9c39a", "#47607a", "#a9b8c4", "#243447"],
    abilities: [
      ability("steel-swing", "Steel Swing", "Reliable melee strike.", { damage: "1d8+4" }),
      ability("shield-bash", "Shield Bash", "Hit and stagger a nearby foe.", { damage: "1d6+4", condition: "staggered", cooldown: 2 }),
      ability("challenge", "Challenge", "Mark a foe; it deals less damage to allies.", { damage: null, condition: "challenged", cooldown: 2 }),
      ability("shield-wall", "Shield Wall", "Brace and gain +3 Defense until your next turn.", { target: "self", buff: "guarded", cooldown: 3 }),
      ability("crushing-blow", "Crushing Blow", "Heavy attack with a larger damage die.", { damage: "1d12+4", cooldown: 2 }),
    ],
    utility: "Can force stuck doors and protect allies during hazards.",
  },
  {
    id: "kaia-redhand",
    name: "Kaia Redhand",
    className: "Berserker",
    role: "Explosive melee damage",
    tagline: "I have a plan. The plan is loud.",
    stats: { strength: 5, dexterity: 2, intellect: 0, insight: 1, presence: 2 },
    maxHp: 38, defense: 13, move: 5, initiative: 2,
    palette: ["#e4b091", "#8e2f2f", "#d6a84f", "#3f2020"],
    abilities: [
      ability("battle-axe", "Battle Axe", "Hard-hitting melee attack.", { damage: "1d10+5" }),
      ability("rage", "Rage", "Gain power for three turns at the cost of Defense.", { target: "self", buff: "raging", cooldown: 4 }),
      ability("cleave", "Cleave", "Strike every adjacent enemy.", { target: "area", damage: "1d8+4", radius: 1, cooldown: 2 }),
      ability("reckless-strike", "Reckless Strike", "Roll with advantage; become exposed afterward.", { damage: "1d12+5", buff: "reckless", cooldown: 2 }),
      ability("war-cry", "War Cry", "Frighten a nearby foe and rally allies.", { range: 3, damage: null, condition: "frightened", cooldown: 3 }),
    ],
    utility: "Excellent at intimidation, athletics, and smashing questionable architecture.",
  },
  {
    id: "nyx-quickstep",
    name: "Nyx Quickstep",
    className: "Shadow",
    role: "Mobile precision striker",
    tagline: "Locks are just puzzles that forgot they were fun.",
    stats: { strength: 1, dexterity: 5, intellect: 2, insight: 2, presence: 2 },
    maxHp: 27, defense: 15, move: 6, initiative: 5,
    palette: ["#c99d85", "#43355f", "#8a74b5", "#1e1729"],
    abilities: [
      ability("quick-blade", "Quick Blade", "Fast finesse attack.", { damage: "1d6+5", stat: "dexterity" }),
      ability("sneak-attack", "Sneak Attack", "Deals extra damage when an ally is adjacent to the target.", { damage: "2d6+5", stat: "dexterity", cooldown: 2 }),
      ability("throwing-knife", "Throwing Knife", "Ranged finesse attack.", { range: 5, damage: "1d6+5", stat: "dexterity" }),
      ability("vanish", "Vanish", "Become hidden until attacking or taking damage.", { target: "self", buff: "hidden", cooldown: 3 }),
      ability("dirty-trick", "Dirty Trick", "Blind a foe for one turn.", { damage: "1d4+3", stat: "dexterity", condition: "blinded", cooldown: 3 }),
    ],
    utility: "Can pick locks, detect traps, hide, and scout private routes.",
  },
  {
    id: "orin-wildmark",
    name: "Orin Wildmark",
    className: "Warden",
    role: "Ranged hunter",
    tagline: "Tracks don't lie. People do that constantly.",
    stats: { strength: 2, dexterity: 4, intellect: 1, insight: 4, presence: 1 },
    maxHp: 31, defense: 14, move: 5, initiative: 4,
    palette: ["#c88f67", "#395b3e", "#8ca66a", "#24382b"],
    abilities: [
      ability("longbow", "Longbow", "Accurate ranged attack.", { range: 7, damage: "1d8+4", stat: "dexterity" }),
      ability("mark-target", "Mark Target", "Marked target takes +2 damage from the party.", { range: 7, damage: null, condition: "marked", cooldown: 2 }),
      ability("volley", "Volley", "Rain arrows over a small area.", { range: 6, radius: 1, target: "area", damage: "1d6+3", stat: "dexterity", cooldown: 3 }),
      ability("wolf-call", "Wolf Call", "Spectral hound bites and slows a target.", { range: 5, damage: "1d6+2", stat: "insight", condition: "slowed", cooldown: 3 }),
      ability("trail-step", "Trail Step", "Gain two movement and ignore difficult terrain this turn.", { target: "self", buff: "trailstep", cooldown: 2 }),
    ],
    utility: "Reads tracks, finds safe camps, spots ambushes, and navigates wilderness.",
  },
  {
    id: "sera-emberglass",
    name: "Sera Emberglass",
    className: "Arcanist",
    role: "Area spell damage",
    tagline: "If the room is on fire, the experiment is progressing.",
    stats: { strength: 0, dexterity: 2, intellect: 5, insight: 2, presence: 2 },
    maxHp: 24, defense: 12, move: 4, initiative: 2,
    palette: ["#e2b68f", "#284b7a", "#e08f45", "#17263d"],
    abilities: [
      ability("ember-bolt", "Ember Bolt", "Ranged arcane attack.", { range: 6, damage: "1d8+5", stat: "intellect" }),
      ability("fireburst", "Fireburst", "Explodes around a target tile.", { range: 6, radius: 1, target: "area", damage: "2d6+3", stat: "intellect", cooldown: 3 }),
      ability("blink", "Blink", "Teleport up to four tiles.", { target: "tile", range: 4, movement: "teleport", cooldown: 2 }),
      ability("arcane-shield", "Arcane Shield", "Gain +4 Defense for one round.", { target: "self", buff: "arcane-shield", cooldown: 3 }),
      ability("frost-spark", "Frost Spark", "Damage and slow a foe.", { range: 5, damage: "1d6+4", stat: "intellect", condition: "slowed", cooldown: 2 }),
    ],
    utility: "Recognizes runes, magical effects, ancient devices, and unstable portals.",
  },
  {
    id: "mira-dawnwell",
    name: "Mira Dawnwell",
    className: "Luminary",
    role: "Healing and protection",
    tagline: "Try not to die somewhere inconvenient.",
    stats: { strength: 1, dexterity: 1, intellect: 2, insight: 5, presence: 3 },
    maxHp: 29, defense: 13, move: 4, initiative: 1,
    palette: ["#d7ad8b", "#efe0a2", "#6a8d73", "#415748"],
    abilities: [
      ability("sun-mace", "Sun Mace", "Simple melee strike.", { damage: "1d6+1" }),
      ability("mend", "Mend", "Restore an ally's health.", { range: 5, target: "ally", damage: null, heal: "1d8+5", stat: "insight" }),
      ability("sanctuary", "Sanctuary", "Protect an ally with +3 Defense.", { range: 4, target: "ally", buff: "sanctuary", cooldown: 2 }),
      ability("radiant-pulse", "Radiant Pulse", "Damage nearby enemies and heal nearby allies.", { target: "area", radius: 2, damage: "1d6+3", heal: "1d4+2", stat: "insight", cooldown: 3 }),
      ability("revive", "Revive", "Return a downed ally to 35% health.", { range: 2, target: "ally", revive: true, cooldown: 5 }),
    ],
    utility: "Reads people well, treats injuries, calms frightened NPCs, and blesses camps.",
  },
  {
    id: "aldren-oathfire",
    name: "Aldren Oathfire",
    className: "Oathkeeper",
    role: "Guardian striker",
    tagline: "I made an oath. I forgot the exact wording, but it was inspiring.",
    stats: { strength: 4, dexterity: 1, intellect: 1, insight: 3, presence: 4 },
    maxHp: 36, defense: 15, move: 4, initiative: 1,
    palette: ["#c89d78", "#d9b14b", "#8d3f3f", "#51302c"],
    abilities: [
      ability("oathblade", "Oathblade", "Reliable melee strike.", { damage: "1d8+4" }),
      ability("smite", "Smite", "Radiant strike; stronger against cursed foes.", { damage: "1d10+5", cooldown: 2 }),
      ability("guard-ally", "Guard Ally", "Take part of an adjacent ally's next damage.", { range: 1, target: "ally", buff: "guarded-by-ally", cooldown: 2 }),
      ability("steadfast-aura", "Steadfast Aura", "Nearby allies resist fear and gain Defense.", { target: "self", buff: "aura", cooldown: 4 }),
      ability("judgment", "Judgment", "Challenge a distant foe with radiant force.", { range: 4, damage: "1d6+4", stat: "presence", condition: "challenged", cooldown: 3 }),
    ],
    utility: "Excels at negotiation, oaths, morale, and reading institutions or heraldry.",
  },
  {
    id: "fen-mosswhisper",
    name: "Fen Mosswhisper",
    className: "Wildcaller",
    role: "Control and shapeshifting",
    tagline: "The mushrooms say we should leave. They are usually dramatic.",
    stats: { strength: 2, dexterity: 2, intellect: 2, insight: 5, presence: 1 },
    maxHp: 30, defense: 13, move: 4, initiative: 2,
    palette: ["#b98d70", "#65764c", "#a08b64", "#35402c"],
    abilities: [
      ability("thorn-whip", "Thorn Whip", "Pull a foe one tile closer.", { range: 4, damage: "1d6+4", stat: "insight", condition: "pulled" }),
      ability("entangle", "Entangle", "Roots enemies in a small area.", { range: 5, radius: 1, target: "area", damage: null, condition: "rooted", cooldown: 3 }),
      ability("bear-form", "Bear Form", "Gain health, melee power, and lower range temporarily.", { target: "self", buff: "bear-form", cooldown: 4 }),
      ability("nature-gift", "Nature's Gift", "Heal an ally over time.", { range: 4, target: "ally", heal: "1d6+4", stat: "insight", cooldown: 2 }),
      ability("swarm", "Moth Swarm", "Distract and damage a target.", { range: 5, damage: "1d6+3", stat: "insight", condition: "blinded", cooldown: 3 }),
    ],
    utility: "Communes with animals and plants, identifies natural hazards, and forages supplies.",
  },
  {
    id: "puck-brightnote",
    name: "Puck Brightnote",
    className: "Troubadour",
    role: "Buffs, debuffs, social play",
    tagline: "I can fix this with diplomacy or an aggressively catchy chorus.",
    stats: { strength: 1, dexterity: 3, intellect: 2, insight: 2, presence: 5 },
    maxHp: 28, defense: 14, move: 5, initiative: 3,
    palette: ["#d8a783", "#8d3f75", "#d39f4d", "#41213b"],
    abilities: [
      ability("rapier", "Rapier", "Precise melee strike.", { damage: "1d6+3", stat: "dexterity" }),
      ability("inspire", "Inspire", "Give an ally +2 to attacks and checks for one round.", { range: 5, target: "ally", buff: "inspired", cooldown: 2 }),
      ability("cutting-joke", "Cutting Joke", "Psychic sting that weakens a foe.", { range: 5, damage: "1d6+5", stat: "presence", condition: "shaken", cooldown: 2 }),
      ability("distract", "Distract", "Force a foe to lose reactions and lower Defense.", { range: 5, damage: null, condition: "distracted", cooldown: 2 }),
      ability("encore", "Encore", "Refresh one ally's shortest cooldown.", { range: 4, target: "ally", cooldown: 4 }),
    ],
    utility: "Best social negotiator; performs, deceives, distracts, and remembers rumors.",
  },
  {
    id: "tink-fusebox",
    name: "Tink Fusebox",
    className: "Engineer",
    role: "Traps and gadgets",
    tagline: "It's not exploding. It's venting enthusiasm.",
    stats: { strength: 1, dexterity: 3, intellect: 5, insight: 2, presence: 1 },
    maxHp: 27, defense: 13, move: 4, initiative: 3,
    palette: ["#c49570", "#94552f", "#7697a8", "#3d342e"],
    abilities: [
      ability("wrench", "Wrench", "Improvised melee strike.", { damage: "1d6+2", stat: "dexterity" }),
      ability("bomb", "Clockwork Bomb", "Area blast after a satisfying fuse animation.", { range: 5, radius: 1, target: "area", damage: "2d6+3", stat: "intellect", cooldown: 3 }),
      ability("turret", "Pocket Turret", "Deploy a tiny auto-firing construct.", { target: "tile", range: 3, summon: "turret", cooldown: 4 }),
      ability("snare", "Spring Snare", "Root the first enemy entering a tile.", { target: "tile", range: 3, summon: "trap", cooldown: 2 }),
      ability("overclock", "Overclock", "Gain movement and attack power for one round.", { target: "self", buff: "overclocked", cooldown: 3 }),
    ],
    utility: "Repairs mechanisms, disables traps, identifies machinery, and improvises tools.",
  },
  {
    id: "vel-raingloom",
    name: "Vel Raingloom",
    className: "Hexbinder",
    role: "Risk-reward caster",
    tagline: "Technically the curse is under control.",
    stats: { strength: 0, dexterity: 2, intellect: 4, insight: 2, presence: 5 },
    maxHp: 26, defense: 13, move: 4, initiative: 2,
    palette: ["#b98f7b", "#4b315f", "#814f8e", "#251c2e"],
    abilities: [
      ability("hex-bolt", "Hex Bolt", "Ranged curse attack.", { range: 6, damage: "1d8+5", stat: "presence" }),
      ability("curse", "Withering Curse", "Reduce a foe's Defense and damage.", { range: 6, damage: null, condition: "cursed", cooldown: 2 }),
      ability("life-drain", "Life Drain", "Damage a foe and heal for half the damage.", { range: 4, damage: "1d8+4", stat: "presence", drain: true, cooldown: 2 }),
      ability("dark-bargain", "Dark Bargain", "Spend 5 HP to refresh all other cooldowns.", { target: "self", sacrifice: 5, cooldown: 5 }),
      ability("doom-ring", "Doom Ring", "Damage and weaken enemies around you.", { target: "area", radius: 2, damage: "1d6+4", stat: "presence", condition: "shaken", cooldown: 4 }),
    ],
    utility: "Recognizes curses, bargains with strange entities, and reads forbidden symbolism.",
  },
  {
    id: "ashi-sevensteps",
    name: "Ashi Sevensteps",
    className: "Wayfarer Monk",
    role: "Mobile control fighter",
    tagline: "The shortest path is usually through the problem.",
    stats: { strength: 2, dexterity: 5, intellect: 1, insight: 4, presence: 1 },
    maxHp: 30, defense: 15, move: 7, initiative: 5,
    palette: ["#c99778", "#9b743e", "#6d5a4c", "#342a25"],
    abilities: [
      ability("palm-strike", "Palm Strike", "Fast unarmed attack.", { damage: "1d6+5", stat: "dexterity" }),
      ability("flurry", "Flurry", "Two rapid strikes resolved together.", { damage: "2d6+4", stat: "dexterity", cooldown: 2 }),
      ability("stunning-strike", "Stunning Strike", "Chance to stun a foe for one turn.", { damage: "1d6+4", stat: "dexterity", condition: "stunned", cooldown: 3 }),
      ability("deflect", "Deflect", "Gain strong ranged Defense until next turn.", { target: "self", buff: "deflecting", cooldown: 2 }),
      ability("wind-step", "Wind Step", "Dash up to five tiles without provoking danger.", { target: "tile", range: 5, movement: "dash", cooldown: 2 }),
    ],
    utility: "Best climber and acrobat; crosses hazards and reaches otherwise inaccessible places.",
  },
]);

export const ENEMIES = Object.freeze({
  boggobbler: { id: "boggobbler", name: "Bog Gobbler", glyph: "G", maxHp: 18, defense: 12, move: 4, initiative: 2, attack: { name: "Rusty Cleaver", range: 1, bonus: 3, damage: "1d6+2" }, palette: ["#83a64f", "#4c6f33", "#b78a48"] },
  boneguard: { id: "boneguard", name: "Boneguard", glyph: "S", maxHp: 22, defense: 14, move: 3, initiative: 1, attack: { name: "Grave Spear", range: 2, bonus: 4, damage: "1d8+2" }, palette: ["#d6d0b0", "#8e8d7a", "#5b5c56"] },
  mireSpider: { id: "mireSpider", name: "Mire Spider", glyph: "X", maxHp: 14, defense: 13, move: 6, initiative: 5, attack: { name: "Venom Bite", range: 1, bonus: 4, damage: "1d6+2", condition: "slowed" }, palette: ["#5b4a68", "#9581a4", "#2a2431"] },
  emberImp: { id: "emberImp", name: "Ember Imp", glyph: "I", maxHp: 15, defense: 13, move: 5, initiative: 4, attack: { name: "Cinder Spit", range: 5, bonus: 4, damage: "1d6+3" }, palette: ["#d95c38", "#f29d49", "#6b2d2a"] },
  graveHound: { id: "graveHound", name: "Grave Hound", glyph: "H", maxHp: 20, defense: 13, move: 6, initiative: 4, attack: { name: "Grave Bite", range: 1, bonus: 5, damage: "1d8+2" }, palette: ["#4e5962", "#8d999f", "#272c31"] },
  ironBrute: { id: "ironBrute", name: "Iron Brute", glyph: "B", maxHp: 34, defense: 15, move: 3, initiative: 0, attack: { name: "Hammer Fist", range: 1, bonus: 5, damage: "1d10+3" }, palette: ["#777b7c", "#b0844a", "#383c3d"] },
  bellWarden: { id: "bellWarden", name: "Bell Warden", glyph: "W", maxHp: 72, defense: 16, move: 4, initiative: 3, boss: true, attack: { name: "Toll of Ruin", range: 4, bonus: 6, damage: "1d10+4", condition: "shaken" }, palette: ["#665577", "#a088a3", "#30273a"] },
});

export const MAPS = Object.freeze({
  villageRoad: [
    "############",
    "#..........#",
    "#..##......#",
    "#.......#..#",
    "#..~~...#..#",
    "#..~~......#",
    "#..........#",
    "############",
  ],
  chapelCrypt: [
    "############",
    "#....#.....#",
    "#....#..C..#",
    "#..........#",
    "#.##....##.#",
    "#....F.....#",
    "#..........#",
    "############",
  ],
  blackhollowSquare: [
    "############",
    "#....#.....#",
    "#....#..C..#",
    "#..........#",
    "#..##......#",
    "#.....F....#",
    "#..........#",
    "############",
  ],
  bellTower: [
    "############",
    "#....#.....#",
    "#....#.....#",
    "#..........#",
    "#..##..##..#",
    "#......F...#",
    "#..C.......#",
    "############",
  ],
  genericDungeon: [
    "############",
    "#..........#",
    "#..##......#",
    "#......##..#",
    "#..F.......#",
    "#......C...#",
    "#..........#",
    "############",
  ],
});

const scene = (id, type, title, text, extra = {}) => Object.freeze({ id, type, title, text, ...extra });

const compactAdventure = ({ id, number, title, subtitle, tone, region, enemy, boss = "ironBrute", hook, challenge, secret, choiceA, choiceB, accent }) => Object.freeze({
  id, number, title, subtitle, tone, region, accent,
  estimatedMinutes: 20,
  intro: hook,
  scenes: [
    scene("arrival", "story", `Arrival: ${region}`, hook, { next: "crossroads" }),
    scene("crossroads", "party-choice", "The party chooses a route", "The obvious route is rarely the only route.", {
      choices: [
        { id: "bold", label: choiceA, detail: "Faster, louder, and likely to draw attention.", next: "challenge" },
        { id: "careful", label: choiceB, detail: "Slower, safer, and more likely to uncover useful information.", next: "challenge" },
        { id: "observe", label: "Stop and study the area", detail: "Risk time in exchange for clues.", next: "challenge", flag: "patient-route" },
      ],
    }),
    scene("challenge", "skill", "A problem without a sword-shaped solution", challenge, { stat: "insight", dc: 12, successNext: "secret", failNext: "ambush" }),
    scene("secret", "private", "Someone notices something", secret, {
      choices: [
        { id: "share", label: "Tell the party immediately", flag: "secret-shared" },
        { id: "pocket", label: "Keep the discovery private", flag: "secret-kept" },
        { id: "test", label: "Quietly test what you found", flag: "secret-tested" },
      ], next: "ambush",
    }),
    scene("ambush", "combat", "Steel, claws, and bad timing", `A ${ENEMIES[enemy].name} pack blocks the route.`, { map: "genericDungeon", enemies: [enemy, enemy, enemy], next: "boss" }),
    scene("boss", "combat", "The final obstacle", "The adventure's true threat finally steps into view.", { map: "genericDungeon", enemies: [boss], next: "ending", boss: true }),
    scene("ending", "ending", "Adventure complete", "The party survives, richer in gold, scars, and stories nobody else would believe.", { rewardGold: 180, rewardXp: 120 }),
  ],
});

const BLACKHOLLOW = Object.freeze({
  id: "bells-blackhollow", number: 4, title: "The Bells of Blackhollow", subtitle: "No bell has rung here in seventy-three years. Tonight, all seven rang at once.", tone: "Gothic mystery", region: "Blackhollow", accent: "#7e6a9d", estimatedMinutes: 45,
  intro: "Rain needles the road as Blackhollow appears below: slate roofs, boarded windows, and a crooked bell tower cutting into a bruised sky. The seventh bell rings. Every light in town goes dark.",
  scenes: [
    scene("arrival", "story", "The Seventh Bell", "Rain needles the road as Blackhollow appears below. A bell rings once, then six answering bells roll through the empty valley. Nobody in the party can see seven towers.", { next: "gate-choice" }),
    scene("gate-choice", "party-choice", "How do you enter Blackhollow?", "The front gate hangs open. Muddy child-sized footprints disappear into the orchard while lamplight flickers beneath an old mill.", {
      choices: [
        { id: "gate", label: "Walk through the front gate openly", detail: "Direct. Respectable. Very visible.", next: "square" },
        { id: "orchard", label: "Follow the small footprints through the orchard", detail: "Potential clue; higher ambush risk.", next: "orchard-check", flag: "followed-footprints" },
        { id: "mill", label: "Investigate the lit mill", detail: "Someone is awake in a town pretending to sleep.", next: "mill-private", flag: "visited-mill" },
        { id: "ridge", label: "Circle above town and study the bell tower", detail: "Safer route with a better view.", next: "ridge-check", flag: "scouted-ridge" },
      ],
    }),
    scene("orchard-check", "skill", "Footprints in the mud", "The prints repeatedly stop beneath branches, as though whoever made them was listening for something above.", { stat: "insight", dc: 11, successText: "You find black wax pressed into the bark: a child's handprint around an unfamiliar spiral seal.", failText: "A branch snaps. Shapes move between the trees.", successNext: "mill-private", failNext: "orchard-fight" }),
    scene("ridge-check", "skill", "Counting towers", "From the ridge you can see the chapel tower, the foundry whistle, and five smaller belfries. The impossible seventh sound came from underground.", { stat: "intellect", dc: 12, successText: "You map the echoes and identify a crypt entrance beneath the chapel.", failText: "Lightning destroys your bearings and something starts climbing the ridge behind you.", successNext: "square", failNext: "orchard-fight" }),
    scene("mill-private", "private", "A secret in the mill", "One hero notices a silver key hanging inside the miller's locked office and a ledger page bearing the same spiral seal seen around town.", {
      choices: [
        { id: "take-key", label: "Pocket the silver key without telling anyone", flag: "silver-key-secret" },
        { id: "share-key", label: "Show the key and ledger to the party", flag: "silver-key-shared" },
        { id: "leave-key", label: "Leave it untouched and memorize the seal", flag: "seal-memorized" },
      ], next: "square",
    }),
    scene("orchard-fight", "combat", "Something in the orchard", "Mire spiders spill from a collapsed cider shed while a grave hound circles behind the party.", { map: "villageRoad", enemies: ["mireSpider", "mireSpider", "graveHound"], next: "square" }),
    scene("square", "party-choice", "Blackhollow Square", "A terrified innkeeper waves from behind a barricaded window. The chapel doors stand open. On the opposite side of the square, three silent children watch from beneath identical black umbrellas.", {
      choices: [
        { id: "inn", label: "Question the innkeeper", detail: "Learn what happened before the bells started.", next: "inn-check", flag: "met-innkeeper" },
        { id: "chapel", label: "Enter the abandoned chapel", detail: "Follow the strongest trail toward the hidden bells.", next: "chapel-fight", flag: "entered-chapel" },
        { id: "children", label: "Approach the children", detail: "They have not moved once.", next: "children-check", flag: "approached-children" },
      ],
    }),
    scene("inn-check", "skill", "The innkeeper's story", "Marta Vale swears the bells began after Father Orren reopened the sealed crypt. She stops talking whenever the children outside move.", { stat: "presence", dc: 12, successText: "Marta admits Father Orren begged her to destroy a bronze handbell hidden in the chapel crypt.", failText: "Marta panics, shuts the window, and refuses to speak again.", successNext: "chapel-fight", failNext: "chapel-fight", flagOnSuccess: "knows-handbell" }),
    scene("children-check", "skill", "Children beneath black umbrellas", "Their faces are pale but warm. They answer every question one breath too late, as if listening to someone beneath the street.", { stat: "insight", dc: 13, successText: "They are alive and terrified. A voice under the square is forcing them to repeat its words.", failText: "One child smiles too widely. The church bell crashes once and the children scatter.", successNext: "chapel-fight", failNext: "chapel-fight", flagOnSuccess: "children-freed" }),
    scene("chapel-fight", "combat", "The Chapel of Saint Vey", "Boneguards rise between shattered pews as the bell ropes begin pulling themselves.", { map: "chapelCrypt", enemies: ["boneguard", "boneguard", "emberImp", "boneguard"], next: "crypt-choice" }),
    scene("crypt-choice", "party-choice", "Beneath the chapel", "A spiral staircase descends around a shaft where enormous bronze chains vanish into darkness. One passage bears fresh footprints. Another glows with furnace light.", {
      choices: [
        { id: "footprints", label: "Follow Father Orren's footprints", detail: "Find the priest before whatever found him does.", next: "orrens-secret", flag: "followed-orren" },
        { id: "furnace", label: "Follow the furnace glow", detail: "Disable whatever powers the hidden bell machinery.", next: "chain-check", flag: "found-bell-engine" },
        { id: "listen", label: "Stop and listen to the chains", detail: "Risk a strange mental contact for information.", next: "whisper-check", flag: "heard-below" },
      ],
    }),
    scene("orrens-secret", "private", "Father Orren's confession", "A dying priest presses a cracked bronze clapper into one hero's hand. He whispers that the Bell Warden cannot command anyone carrying it—but asks that the party never learn he caused the awakening.", {
      choices: [
        { id: "promise", label: "Promise to keep Orren's guilt secret", flag: "protected-orren" },
        { id: "truth", label: "Tell him the party deserves the truth", flag: "expose-orren" },
        { id: "clapper", label: "Take the clapper and say nothing", flag: "warding-clapper" },
      ], next: "chain-check",
    }),
    scene("whisper-check", "skill", "The voice beneath the bells", "A voice crawls through the bronze: RETURN WHAT WAS STOLEN AND BLACKHOLLOW MAY KEEP ITS NAME.", { stat: "presence", dc: 14, successText: "You resist the compulsion and learn the Warden is bound to a stolen funerary bell-clapper.", failText: "The command steals a fragment of courage; the next battle begins under pressure.", successNext: "chain-check", failNext: "chain-check", flagOnSuccess: "knows-warden-binding" }),
    scene("chain-check", "skill", "The impossible bell engine", "Seven chains pass through an ancient gear assembly. One drives upward. Six drive down into burial chambers.", { stat: "intellect", dc: 13, successText: "You jam three gears, weakening the Warden before the final fight.", failText: "The mechanism screams awake and summons another guardian.", successNext: "bell-warden", failNext: "engine-fight", flagOnSuccess: "warden-weakened" }),
    scene("engine-fight", "combat", "The bell engine wakes", "An Iron Brute tears itself free from the mechanism while ember imps rain from the gears.", { map: "bellTower", enemies: ["ironBrute", "emberImp", "emberImp"], next: "bell-warden" }),
    scene("bell-warden", "combat", "The Bell Warden", "The hidden seventh bell hangs over a bottomless chamber. Beneath it stands the Bell Warden, draped in funeral cloth and bronze chains. Every toll shakes dust from the bones of the crypt.", { map: "bellTower", enemies: ["bellWarden", "boneguard", "boneguard"], next: "ending", boss: true }),
    scene("ending", "ending", "When the bells go silent", "Dawn reaches Blackhollow as though it had been waiting outside the valley all night. The surviving townsfolk emerge slowly. Somewhere beneath the chapel, one final chain gives a harmless little clink—and stops.", { rewardGold: 420, rewardXp: 300, legend: "Silenced the impossible seventh bell of Blackhollow." }),
  ],
});

export const ADVENTURES = Object.freeze([
  compactAdventure({ id: "goblins-greenvale", number: 1, title: "The Goblins of Greenvale", subtitle: "A stolen harvest, a broken bridge, and goblins with surprisingly strong opinions about turnips.", tone: "Classic adventure", region: "Greenvale", enemy: "boggobbler", boss: "ironBrute", hook: "Greenvale's harvest wagons have vanished on the old king's road, leaving only tiny boot prints and one extremely offended goose.", challenge: "A rope bridge has been cut in three places. Crossing quietly may reveal who is watching from the ridge.", secret: "You spot a goblin peace-token hidden beneath a wagon wheel. Somebody tried to negotiate before the raid.", choiceA: "Follow the wagon tracks into the gorge", choiceB: "Climb the ridge and approach from above", accent: "#7da75a" }),
  compactAdventure({ id: "forgotten-king", number: 2, title: "Crypt of the Forgotten King", subtitle: "The dead remember a ruler history tried to erase.", tone: "Undead dungeon", region: "The Barrow March", enemy: "boneguard", boss: "bellWarden", hook: "A sinkhole opens beneath a shepherd's field, revealing royal stairs descending into a tomb whose king appears in no history book.", challenge: "A stone door presents five crowns and a warning written in mirrored script.", secret: "One crown bears your family name in a language you should not be able to read.", choiceA: "Descend through the ceremonial stair", choiceB: "Enter through the collapsed burial tunnel", accent: "#9a9376" }),
  compactAdventure({ id: "whispering-wood", number: 3, title: "The Witch of Whispering Wood", subtitle: "The forest is talking. The witch may be the only one listening correctly.", tone: "Mystery and magic", region: "Whispering Wood", enemy: "mireSpider", boss: "emberImp", hook: "Every child in Alder Fen drew the same crooked house last night. By morning, the house existed in the forest.", challenge: "The path loops back on itself unless the party follows sounds that do not belong in a forest.", secret: "The supposed witch has been leaving wards to keep something older asleep.", choiceA: "Follow the lanterns between the trees", choiceB: "Ignore the path and follow the creek", accent: "#6f8f6f" }),
  BLACKHOLLOW,
  compactAdventure({ id: "skull-coast", number: 5, title: "Raiders of Skull Coast", subtitle: "Pirates, storm caves, and a map tattooed on the wrong person.", tone: "Pirate adventure", region: "Skull Coast", enemy: "boggobbler", boss: "ironBrute", hook: "A raider ship has grounded itself on a reef during a storm, and half the crew is searching the coast for something more valuable than gold.", challenge: "A tide cave floods in repeating surges, leaving only seconds to move between safe ledges.", secret: "The raiders are fleeing their own captain, who made a bargain with something beneath the lighthouse.", choiceA: "Board the wreck during the storm", choiceB: "Shadow the raiders along the cliff path", accent: "#4f8195" }),
  compactAdventure({ id: "dragon-mountain", number: 6, title: "The Dragon Beneath the Mountain", subtitle: "Something vast is breathing under Ironpeak, and the dwarves stopped answering letters.", tone: "Dragon hunt", region: "Ironpeak", enemy: "emberImp", boss: "ironBrute", hook: "The mountain exhales smoke through mine shafts that have been cold for a century. At night, something scratches beneath the town cistern.", challenge: "Ancient ventilation gates can redirect heat away from the trapped miners—but only if the correct sequence is restored.", secret: "The dragon Vharosk is wounded and defending an egg from the miners who woke it.", choiceA: "Enter through the royal mine", choiceB: "Scale the abandoned chimney shaft", accent: "#b06a3c" }),
  compactAdventure({ id: "moonstone-manor", number: 7, title: "Murder at Moonstone Manor", subtitle: "Eight guests. One locked room. Several people lying badly.", tone: "Whodunit", region: "Moonstone Manor", enemy: "graveHound", boss: "bellWarden", hook: "Lord Moonstone is dead behind a door locked from the inside. The storm has washed out the road, and every guest has a reason to want him gone.", challenge: "The study contains too many clues—several were planted after the murder.", secret: "You recognize the victim's final handwriting as a message written under magical compulsion.", choiceA: "Interrogate the guests immediately", choiceB: "Search the manor before anyone can move evidence", accent: "#78638f" }),
  compactAdventure({ id: "irondeep", number: 8, title: "The Mines of Irondeep", subtitle: "The miners dug through a wall that was never meant to have another side.", tone: "Underground expedition", region: "Irondeep", enemy: "ironBrute", boss: "bellWarden", hook: "Irondeep's newest tunnel breaks into a polished black corridor older than the mountain itself. Then the lift stops returning.", challenge: "A failing lift mechanism can carry the party down, but only after redistributing weight and repairing the brake gear.", secret: "The miners deliberately hid the first chamber from the crown for months.", choiceA: "Repair the main lift", choiceB: "Descend through the ventilation chain", accent: "#8a745b" }),
  compactAdventure({ id: "crimson-moon", number: 9, title: "Curse of the Crimson Moon", subtitle: "Every suspect swears they are not the beast. One of them is correct.", tone: "Shapeshifter hunt", region: "Redfen", enemy: "graveHound", boss: "ironBrute", hook: "The crimson moon rises three nights early. Livestock disappear, doors are clawed from the inside, and the village hunter refuses to touch silver.", challenge: "Tracks split into human and animal prints at the same point without either set approaching it.", secret: "The curse moves between hosts when the current bearer is killed.", choiceA: "Set a trap at the sheep pens", choiceB: "Watch the suspected families from the old watchtower", accent: "#9e4f55" }),
  compactAdventure({ id: "clockwork-tower", number: 10, title: "The Clockwork Tower", subtitle: "A wizard died. His tower did not get the message.", tone: "Traps and puzzles", region: "Brassmere", enemy: "ironBrute", boss: "emberImp", hook: "At noon each day the Clockwork Tower rearranges the streets around it by one block. Today it moved twice.", challenge: "Three rotating rooms must be aligned without triggering the tower's mechanical guardians.", secret: "The tower is not malfunctioning; it is trying to point toward something beneath the city.", choiceA: "Enter when the gears open the front gate", choiceB: "Ride the exterior counterweight to an upper floor", accent: "#b38a47" }),
  compactAdventure({ id: "sunken-temple", number: 11, title: "Secrets of the Sunken Temple", subtitle: "The lake drained overnight. Everybody saw the stairs.", tone: "Flooded ruins", region: "Lake Varro", enemy: "mireSpider", boss: "bellWarden", hook: "A drought exposes a temple beneath Lake Varro for the first time in living memory. Rain clouds are already gathering upstream.", challenge: "A mosaic floor controls floodgates but several tiles have been removed and sold as souvenirs.", secret: "The temple was built to imprison the lake, not worship it.", choiceA: "Enter through the exposed grand stair", choiceB: "Dive through a collapsed side shrine", accent: "#4d8995" }),
  compactAdventure({ id: "lost-souls", number: 12, title: "The Carnival of Lost Souls", subtitle: "The carnival appears once every thirteen years. Nobody remembers buying a ticket.", tone: "Eerie carnival", region: "The Wandering Fair", enemy: "emberImp", boss: "bellWarden", hook: "Music drifts across an empty field at midnight. By dawn, a carnival stands there, and three townsfolk insist they have worked there all their lives.", challenge: "A hall of mirrors reflects versions of the party making different choices.", secret: "One reflection is not copying you—it is trying to warn you.", choiceA: "Enter through the brightly lit midway", choiceB: "Slip behind the tents through the wagon yard", accent: "#9c557c" }),
  compactAdventure({ id: "stormwatch", number: 13, title: "Siege of Stormwatch", subtitle: "Hold the gate until dawn. The enemy brought something that hates walls.", tone: "Fortress defense", region: "Stormwatch Keep", enemy: "boggobbler", boss: "ironBrute", hook: "The northern watchfires go dark one by one. Stormwatch has one night to prepare before the valley army reaches its walls.", challenge: "The party must choose which damaged defenses to repair with limited labor and timber.", secret: "Someone inside the keep has been opening a postern gate after midnight.", choiceA: "Reinforce the main gate", choiceB: "Lead a sortie to destroy the enemy bridge", accent: "#6f7893" }),
  compactAdventure({ id: "frost-crown", number: 14, title: "The Frost King's Crown", subtitle: "A crown of living ice is turning summer into winter.", tone: "Frozen wilderness", region: "The White Reach", enemy: "graveHound", boss: "ironBrute", hook: "Snow falls on midsummer fields. Far north, a blue column of light rises where the Frost King's tomb was opened by treasure hunters.", challenge: "A frozen ravine can be crossed by reading stress lines before the ice breaks.", secret: "The crown chooses a bearer; destroying it may only release what is trapped inside.", choiceA: "Cross the glacier directly", choiceB: "Follow the hot springs through the ice caves", accent: "#7ca0b8" }),
  compactAdventure({ id: "castle-grim", number: 15, title: "Escape From Castle Grim", subtitle: "No weapons. No map. One guard who desperately wants a promotion.", tone: "Prison escape", region: "Castle Grim", enemy: "boneguard", boss: "ironBrute", hook: "The party wakes in separate cells with their gear missing and a public execution scheduled for sunrise.", challenge: "The cellblock changes guard rotations every seventeen minutes, except one bell is ringing off schedule.", secret: "Another prisoner has your equipment and knows why you were really arrested.", choiceA: "Overpower the next guard patrol", choiceB: "Escape through the old drainage tunnel", accent: "#777a80" }),
  compactAdventure({ id: "shifting-maze", number: 16, title: "The Maze of Archmage Vex", subtitle: "The maze is bored. That is worse than being hungry.", tone: "Reality-bending dungeon", region: "Vex's Maze", enemy: "emberImp", boss: "bellWarden", hook: "A brass door appears in the town square with a note: PLEASE RETURN MY MAZE. IT HAS BECOME OPINIONATED.", challenge: "Hallways rotate when nobody looks directly at them.", secret: "The maze is trying to choose a new owner and has started interviewing the party.", choiceA: "Follow the numbered doors", choiceB: "Ignore the doors and mark the walls", accent: "#805c9a" }),
  compactAdventure({ id: "black-siren", number: 17, title: "The Last Voyage of the Black Siren", subtitle: "A ghost ship arrives exactly on schedule for a voyage nobody booked.", tone: "Ghost ship", region: "Graywater Bay", enemy: "boneguard", boss: "bellWarden", hook: "The Black Siren sails into harbor under full moonlight with no living crew and a passenger manifest containing the party's names.", challenge: "The ship's compass points toward different memories depending on who holds it.", secret: "The final passenger is not dead yet—and is somewhere in town.", choiceA: "Board before the tide turns", choiceB: "Search the harbor records first", accent: "#4e7080" }),
  compactAdventure({ id: "emberfall-war", number: 18, title: "War for Emberfall", subtitle: "Armies collide while a smaller group decides what the battle is actually about.", tone: "Battlefield", region: "Emberfall Plains", enemy: "ironBrute", boss: "bellWarden", hook: "Three armies converge on Emberfall. All believe the same ancient banner beneath the ruined fortress will prove their claim.", challenge: "Cross an active battlefield by reading troop movement instead of fighting every unit.", secret: "The banner is a forgery created centuries ago to end a previous war.", choiceA: "Fight through the shattered village", choiceB: "Use the old aqueduct beneath the battlefield", accent: "#9b634c" }),
  compactAdventure({ id: "hellfire-gates", number: 19, title: "The Gates of Cinderdeep", subtitle: "The sky cracked. Something on the other side filed a claim.", tone: "Infernal invasion", region: "Cinderdeep", enemy: "emberImp", boss: "bellWarden", hook: "A red fracture opens over Cinderdeep, dropping ash and impossible architecture into the streets. The gate widens whenever someone makes a promise they cannot keep.", challenge: "A ring of oath-stones must be reset without speaking a false statement inside the circle.", secret: "The gate was opened deliberately by someone trying to retrieve a lost child.", choiceA: "Assault the gate anchors", choiceB: "Find the person feeding promises into the breach", accent: "#a74d37" }),
  compactAdventure({ id: "sovereigns-tomb", number: 20, title: "The Sovereign's Tomb", subtitle: "Every road, rumor, relic, and mistake has been pointing here.", tone: "Campaign finale", region: "The Hollow Throne", enemy: "boneguard", boss: "bellWarden", hook: "Twenty sealed doors beneath Emberfall open on the same night. Symbols from the party's past adventures illuminate one by one along a stair descending beyond torchlight.", challenge: "The final lock responds not to a password, but to choices the party made in earlier adventures.", secret: "The Sovereign's tomb is empty because the Sovereign has been traveling with the party in borrowed forms.", choiceA: "Open the throne chamber", choiceB: "Search the reliquary for the missing history first", accent: "#a78755" }),
]);

export const ADVENTURE_BY_ID = Object.freeze(Object.fromEntries(ADVENTURES.map((entry) => [entry.id, entry])));
export const HERO_BY_ID = Object.freeze(Object.fromEntries(HEROES.map((entry) => [entry.id, entry])));

export function adventureScene(adventure, sceneId) {
  return adventure?.scenes?.find((entry) => entry.id === sceneId) || null;
}
