// Additional original/general-knowledge trivia for long-term replayability.
// d: 1 = accessible, 2 = medium, 3 = hard. The game ramps difficulty by round.
export const LAST_ONE_ALIVE_EXTRA_TRIVIA = [
  { q: "Which planet is known as the Red Planet?", a: ["Venus", "Mars", "Mercury", "Neptune"], c: 1, d: 1 },
  { q: "What is H2O commonly called?", a: ["Salt", "Water", "Hydrogen peroxide", "Oxygen"], c: 1, d: 1 },
  { q: "How many legs does a spider have?", a: ["6", "8", "10", "12"], c: 1, d: 1 },
  { q: "Which organ pumps blood through the human body?", a: ["Liver", "Heart", "Kidney", "Lung"], c: 1, d: 1 },
  { q: "At sea level, water freezes at what temperature on the Celsius scale?", a: ["0°C", "10°C", "32°C", "100°C"], c: 0, d: 1 },
  { q: "Which gas do plants take in during photosynthesis?", a: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], c: 2, d: 1 },
  { q: "What force keeps planets in orbit around the Sun?", a: ["Magnetism", "Gravity", "Friction", "Electricity"], c: 1, d: 1 },
  { q: "Which blood cells primarily carry oxygen?", a: ["Red blood cells", "Platelets", "White blood cells", "Stem cells"], c: 0, d: 1 },
  { q: "Which part of a plant usually absorbs water from soil?", a: ["Flower", "Roots", "Fruit", "Pollen"], c: 1, d: 1 },
  { q: "What is the center of an atom called?", a: ["Nucleus", "Orbit", "Membrane", "Cell"], c: 0, d: 1 },
  { q: "Which animal is the largest living land animal?", a: ["Giraffe", "African elephant", "Polar bear", "Rhinoceros"], c: 1, d: 1 },
  { q: "Which animal is famous for changing color to blend with its surroundings?", a: ["Chameleon", "Buffalo", "Penguin", "Otter"], c: 0, d: 1 },
  { q: "What do bees collect from flowers to help make honey?", a: ["Sand", "Nectar", "Sapwood", "Dew only"], c: 1, d: 1 },
  { q: "Which animal is an amphibian?", a: ["Frog", "Lizard", "Mouse", "Eagle"], c: 0, d: 1 },
  { q: "A caterpillar eventually becomes what?", a: ["Beetle", "Butterfly or moth", "Spider", "Snail"], c: 1, d: 1 },
  { q: "What is a baby goat called?", a: ["Calf", "Kid", "Foal", "Cub"], c: 1, d: 1 },
  { q: "Which animal is known for building dams?", a: ["Beaver", "Badger", "Fox", "Moose"], c: 0, d: 1 },
  { q: "What is the fastest land animal?", a: ["Cheetah", "Lion", "Horse", "Ostrich"], c: 0, d: 1 },
  { q: "Which bird is associated with delivering babies in folklore?", a: ["Stork", "Raven", "Peacock", "Pelican"], c: 0, d: 1 },
  { q: "Which mammal is capable of true sustained flight?", a: ["Flying squirrel", "Bat", "Sugar glider", "Colugo"], c: 1, d: 1 },
  { q: "What is the capital of Japan?", a: ["Osaka", "Tokyo", "Kyoto", "Nagoya"], c: 1, d: 1 },
  { q: "Which country contains the city of Rome?", a: ["Spain", "Italy", "Greece", "Portugal"], c: 1, d: 1 },
  { q: "Which continent contains Brazil?", a: ["Africa", "South America", "Asia", "Europe"], c: 1, d: 1 },
  { q: "Which ocean lies between the Americas and Europe/Africa?", a: ["Pacific", "Atlantic", "Indian", "Arctic"], c: 1, d: 1 },
  { q: "What is the capital of Canada?", a: ["Toronto", "Vancouver", "Ottawa", "Montreal"], c: 2, d: 1 },
  { q: "The pyramids of Giza are in which country?", a: ["Egypt", "Mexico", "Peru", "Jordan"], c: 0, d: 1 },
  { q: "Which U.S. state is nicknamed the Sunshine State?", a: ["Florida", "Nevada", "Texas", "Arizona"], c: 0, d: 1 },
  { q: "Which country is shaped roughly like a boot?", a: ["Chile", "Italy", "India", "Norway"], c: 1, d: 1 },
  { q: "Which river is strongly associated with ancient Egyptian civilization?", a: ["Nile", "Amazon", "Volga", "Mekong"], c: 0, d: 1 },
  { q: "Mount Everest is part of which mountain range?", a: ["Andes", "Alps", "Himalayas", "Rockies"], c: 2, d: 1 },
  { q: "Who wrote Romeo and Juliet?", a: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], c: 1, d: 1 },
  { q: "Which instrument has black and white keys?", a: ["Violin", "Piano", "Trumpet", "Flute"], c: 1, d: 1 },
  { q: "What color do you get by mixing blue and yellow paint?", a: ["Green", "Purple", "Orange", "Brown"], c: 0, d: 1 },
  { q: "In traditional Western music notation, how many lines are on a standard staff?", a: ["4", "5", "6", "8"], c: 1, d: 1 },
  { q: "Which fairy-tale character leaves behind a glass slipper?", a: ["Cinderella", "Snow White", "Rapunzel", "Goldilocks"], c: 0, d: 1 },
  { q: "Which board game uses properties such as Boardwalk and Park Place in its U.S. edition?", a: ["Clue", "Monopoly", "Risk", "Scrabble"], c: 1, d: 1 },
  { q: "How many letters are in the modern English alphabet?", a: ["24", "25", "26", "28"], c: 2, d: 1 },
  { q: "Which punctuation mark normally ends a direct question?", a: ["Colon", "Question mark", "Semicolon", "Apostrophe"], c: 1, d: 1 },
  { q: "What is 12 multiplied by 12?", a: ["124", "132", "144", "156"], c: 2, d: 1 },
  { q: "How many minutes are in one hour?", a: ["50", "60", "70", "100"], c: 1, d: 1 },
  { q: "Which tool is typically used to drive a nail?", a: ["Hammer", "Wrench", "Level", "Chisel"], c: 0, d: 1 },
  { q: "Which appliance is primarily used to keep food cold?", a: ["Oven", "Refrigerator", "Toaster", "Dryer"], c: 1, d: 1 },
  { q: "What does a thermometer measure?", a: ["Speed", "Temperature", "Weight", "Distance"], c: 1, d: 1 },
  { q: "Which direction is opposite east?", a: ["North", "West", "South", "Up"], c: 1, d: 1 },
  { q: "How many sides does a hexagon have?", a: ["5", "6", "7", "8"], c: 1, d: 1 },
  { q: "Which month normally has 28 days and 29 in leap years?", a: ["January", "February", "March", "April"], c: 1, d: 1 },
  { q: "What is the main ingredient in traditional guacamole?", a: ["Avocado", "Potato", "Cucumber", "Pea"], c: 0, d: 1 },
  { q: "Which grain is traditionally used to make risotto?", a: ["Rice", "Oats", "Rye", "Corn"], c: 0, d: 1 },
  { q: "What dairy product is churned to make butter?", a: ["Cream", "Yogurt", "Whey", "Custard"], c: 0, d: 1 },
  { q: "Which spice is made from dried flower stigmas and is famously expensive?", a: ["Paprika", "Saffron", "Cumin", "Clove"], c: 1, d: 2 },
  { q: "Which planet has the most prominent visible ring system?", a: ["Mars", "Saturn", "Venus", "Mercury"], c: 1, d: 2 },
  { q: "What is the chemical symbol for gold?", a: ["Ag", "Au", "Gd", "Go"], c: 1, d: 2 },
  { q: "Which organ produces insulin?", a: ["Pancreas", "Spleen", "Gallbladder", "Thyroid"], c: 0, d: 2 },
  { q: "Which vitamin is produced in human skin in response to sunlight?", a: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], c: 2, d: 2 },
  { q: "What type of blood vessel carries blood away from the heart?", a: ["Vein", "Artery", "Capillary only", "Lymph node"], c: 1, d: 2 },
  { q: "What is the process by which a liquid changes into a gas at its surface?", a: ["Condensation", "Evaporation", "Freezing", "Sublimation"], c: 1, d: 2 },
  { q: "Which scale is commonly used to describe mineral hardness?", a: ["Richter", "Mohs", "Beaufort", "pH"], c: 1, d: 2 },
  { q: "Which particle has a negative electric charge?", a: ["Proton", "Electron", "Neutron", "Photon"], c: 1, d: 2 },
  { q: "What is the approximate speed of light in a vacuum?", a: ["300 km/s", "3,000 km/s", "300,000 km/s", "30 million km/s"], c: 2, d: 2 },
  { q: "Which layer of Earth is liquid and helps generate the planet's magnetic field?", a: ["Inner core", "Outer core", "Crust", "Upper mantle only"], c: 1, d: 2 },
  { q: "Which scientist formulated the three classical laws of motion?", a: ["Isaac Newton", "Niels Bohr", "Michael Faraday", "Gregor Mendel"], c: 0, d: 2 },
  { q: "Which scientist is associated with natural selection?", a: ["Louis Pasteur", "Charles Darwin", "Nikola Tesla", "Johannes Kepler"], c: 1, d: 2 },
  { q: "DNA stands for what?", a: ["Deoxyribonucleic acid", "Dynamic nitrogen array", "Double nucleotide atom", "Deoxygenated ribose acid"], c: 0, d: 2 },
  { q: "Which organelle is often called the powerhouse of the cell?", a: ["Golgi apparatus", "Mitochondrion", "Lysosome", "Nucleolus"], c: 1, d: 2 },
  { q: "Which gas is most responsible for the fizz in carbonated drinks?", a: ["Carbon dioxide", "Nitrogen", "Hydrogen", "Methane"], c: 0, d: 2 },
  { q: "Which metal is liquid near typical room temperature?", a: ["Mercury", "Aluminum", "Copper", "Iron"], c: 0, d: 2 },
  { q: "What is the pH of a neutral aqueous solution at about room temperature?", a: ["0", "5", "7", "14"], c: 2, d: 2 },
  { q: "What type of electromagnetic radiation has a longer wavelength than visible red light?", a: ["Ultraviolet", "Infrared", "X-ray", "Gamma ray"], c: 1, d: 2 },
  { q: "Which animal is the largest living species of shark?", a: ["Great white shark", "Whale shark", "Hammerhead shark", "Tiger shark"], c: 1, d: 2 },
  { q: "Which animal's fingerprints can be strikingly similar to a human's?", a: ["Koala", "Horse", "Seal", "Gorilla only"], c: 0, d: 2 },
  { q: "Which bird is the largest living bird by height and mass?", a: ["Emu", "Ostrich", "Cassowary", "Albatross"], c: 1, d: 2 },
  { q: "What is a group of lions commonly called?", a: ["Pride", "Pack", "Pod", "Colony"], c: 0, d: 2 },
  { q: "Which marine mammal is known for using rocks as tools to open shellfish?", a: ["Sea otter", "Walrus", "Manatee", "Blue whale"], c: 0, d: 2 },
  { q: "Which animal has the longest neck relative to its familiar body plan among land mammals?", a: ["Giraffe", "Camel", "Llama", "Okapi"], c: 0, d: 2 },
  { q: "Which insect undergoes complete metamorphosis?", a: ["Butterfly", "Silverfish", "Springtail", "Adult mayfly only"], c: 0, d: 2 },
  { q: "Which sea creature has a hard external shell and ten limbs including claws?", a: ["Crab", "Jellyfish", "Sea cucumber", "Sponge"], c: 0, d: 2 },
  { q: "What is the capital of Australia?", a: ["Sydney", "Melbourne", "Canberra", "Perth"], c: 2, d: 2 },
  { q: "Which country has Lisbon as its capital?", a: ["Portugal", "Spain", "Brazil", "Argentina"], c: 0, d: 2 },
  { q: "Which country contains Petra?", a: ["Jordan", "Lebanon", "Turkey", "Israel"], c: 0, d: 2 },
  { q: "Which sea separates much of southern Europe from northern Africa?", a: ["Baltic Sea", "Mediterranean Sea", "Bering Sea", "North Sea"], c: 1, d: 2 },
  { q: "Which African country has Nairobi as its capital?", a: ["Kenya", "Ghana", "Senegal", "Namibia"], c: 0, d: 2 },
  { q: "Which country is home to the ancient city of Angkor?", a: ["Cambodia", "Thailand", "Laos", "Vietnam"], c: 0, d: 2 },
  { q: "Which European capital sits on the River Thames?", a: ["London", "Paris", "Rome", "Madrid"], c: 0, d: 2 },
  { q: "Which country has the maple leaf on its national flag?", a: ["Canada", "Finland", "Austria", "Denmark"], c: 0, d: 2 },
  { q: "Which mountain range forms a natural border between France and Spain?", a: ["Pyrenees", "Carpathians", "Apennines", "Urals"], c: 0, d: 2 },
  { q: "What is the capital of South Korea?", a: ["Busan", "Seoul", "Incheon", "Daegu"], c: 1, d: 2 },
  { q: "Which country is both a continent and a sovereign state?", a: ["Australia", "Greenland", "Madagascar", "Iceland"], c: 0, d: 2 },
  { q: "Which U.S. state contains the Grand Canyon?", a: ["Arizona", "Colorado", "Utah", "Nevada"], c: 0, d: 2 },
  { q: "Which city is famous for canals and gondolas?", a: ["Venice", "Munich", "Geneva", "Dublin"], c: 0, d: 2 },
  { q: "Which country lies immediately south of the United States?", a: ["Mexico", "Guatemala", "Cuba", "Belize"], c: 0, d: 2 },
  { q: "Who painted the Mona Lisa?", a: ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Rembrandt"], c: 0, d: 2 },
  { q: "Which composer became deaf later in life but continued composing major works?", a: ["Beethoven", "Vivaldi", "Chopin", "Debussy"], c: 0, d: 2 },
  { q: "Which literary character fights windmills in a famous novel?", a: ["Don Quixote", "Hamlet", "Odysseus", "Dorian Gray"], c: 0, d: 2 },
  { q: "Which novel begins with the character Ishmael narrating a whaling voyage?", a: ["Moby-Dick", "Treasure Island", "Dracula", "The Time Machine"], c: 0, d: 2 },
  { q: "What is a painting made on wet plaster called?", a: ["Fresco", "Etching", "Collage", "Lithograph"], c: 0, d: 2 },
  { q: "Which string instrument is normally played under the chin with a bow?", a: ["Violin", "Harp", "Mandolin", "Banjo"], c: 0, d: 2 },
  { q: "In theater, what is the written text of a play called?", a: ["Score", "Script", "Palette", "Ledger"], c: 1, d: 2 },
  { q: "Which dance originated in Argentina and Uruguay?", a: ["Tango", "Waltz", "Polka", "Hula"], c: 0, d: 2 },
  { q: "Which art technique uses many tiny dots of color?", a: ["Pointillism", "Cubism", "Impasto", "Chiaroscuro"], c: 0, d: 2 },
  { q: "Which Greek epic is centered on Odysseus's long journey home?", a: ["The Odyssey", "The Aeneid", "Beowulf", "The Divine Comedy"], c: 0, d: 2 },
  { q: "Who wrote Pride and Prejudice?", a: ["Jane Austen", "Emily Brontë", "George Eliot", "Mary Shelley"], c: 0, d: 2 },
  { q: "What is the term for a word that imitates a sound, such as 'buzz'?", a: ["Onomatopoeia", "Hyperbole", "Metaphor", "Alliteration"], c: 0, d: 2 },
  { q: "Which chess piece moves in an L shape?", a: ["Knight", "Bishop", "Rook", "Queen"], c: 0, d: 2 },
  { q: "How many points is a touchdown worth before any extra-point attempt in American football?", a: ["3", "6", "7", "8"], c: 1, d: 2 },
  { q: "How many players from one team are on the court at once in standard basketball?", a: ["5", "6", "7", "9"], c: 0, d: 2 },
  { q: "In baseball, how many strikes normally make an out?", a: ["2", "3", "4", "5"], c: 1, d: 2 },
  { q: "What does 'par' describe in golf?", a: ["Expected strokes for a hole", "Maximum clubs", "Ball diameter", "Tee height"], c: 0, d: 2 },
  { q: "Which sport uses a shuttlecock?", a: ["Badminton", "Squash", "Lacrosse", "Polo"], c: 0, d: 2 },
  { q: "In tennis, what score follows 30?", a: ["35", "40", "45", "50"], c: 1, d: 2 },
  { q: "Which sport features a scrum?", a: ["Rugby", "Basketball", "Baseball", "Fencing"], c: 0, d: 2 },
  { q: "What is the term for three strikes in a row in bowling?", a: ["Turkey", "Eagle", "Hat trick", "Sweep"], c: 0, d: 2 },
  { q: "Which Olympic sport uses épée, foil, and sabre?", a: ["Fencing", "Archery", "Gymnastics", "Rowing"], c: 0, d: 2 },
  { q: "Which game traditionally has 64 squares on its board?", a: ["Chess", "Go", "Backgammon", "Checkers only has 40"], c: 0, d: 2 },
  { q: "What does 'HTTP' begin with?", a: ["Hypertext Transfer", "High Transmission Text", "Hosted Terminal Type", "Hybrid Transfer Token"], c: 0, d: 2 },
  { q: "What does RAM primarily provide in a computer?", a: ["Temporary working memory", "Permanent archival storage", "Internet access", "Audio amplification"], c: 0, d: 2 },
  { q: "Which file extension commonly identifies a JPEG image?", a: [".jpg", ".exe", ".csv", ".wav"], c: 0, d: 2 },
  { q: "What does GPS primarily help determine?", a: ["Location", "Blood pressure", "File size", "Battery chemistry"], c: 0, d: 2 },
  { q: "What does a QR code store for machines to read?", a: ["Encoded data", "Only photographs", "Only sound", "Magnetic charge"], c: 0, d: 2 },
  { q: "Which keyboard shortcut commonly copies selected content on Windows?", a: ["Ctrl+C", "Ctrl+P", "Ctrl+Z", "Ctrl+L"], c: 0, d: 2 },
  { q: "What does URL stand for?", a: ["Uniform Resource Locator", "Universal Routing Language", "User Reference Link", "Unified Resource Ledger"], c: 0, d: 2 },
  { q: "Which unit is commonly used to measure digital storage?", a: ["Byte", "Volt", "Hertz only", "Lumen"], c: 0, d: 2 },
  { q: "What does two-factor authentication add to a login?", a: ["A second verification method", "A second username", "Twice the storage", "A faster network"], c: 0, d: 2 },
  { q: "Which kitchen technique cooks food in hot oil?", a: ["Frying", "Poaching", "Steaming", "Blanching"], c: 0, d: 2 },
  { q: "What is tofu traditionally made from?", a: ["Soybeans", "Chickpeas", "Rice only", "Potatoes"], c: 0, d: 2 },
  { q: "Which cheese is traditionally used in a classic Greek salad?", a: ["Feta", "Cheddar", "Brie", "Gouda"], c: 0, d: 2 },
  { q: "What is the main spirit in a traditional mojito?", a: ["Rum", "Gin", "Whiskey", "Tequila"], c: 0, d: 2 },
  { q: "Which pasta name literally refers to little tongues?", a: ["Linguine", "Rigatoni", "Fusilli", "Penne"], c: 0, d: 3 },
  { q: "What is clarified butter commonly called in South Asian cooking?", a: ["Ghee", "Tahini", "Miso", "Aioli"], c: 0, d: 2 },
  { q: "Which cooking method seals food in a bag and cooks it in a controlled water bath?", a: ["Sous vide", "Braising", "Broiling", "Smoking"], c: 0, d: 2 },
  { q: "What is the primary ingredient in hummus?", a: ["Chickpeas", "Lentils", "White beans only", "Eggplant"], c: 0, d: 2 },
  { q: "Which French mother sauce is based on milk thickened with a white roux?", a: ["Béchamel", "Hollandaise", "Espagnole", "Tomato"], c: 0, d: 3 },
  { q: "Which element is most abundant in the universe?", a: ["Hydrogen", "Oxygen", "Carbon", "Helium"], c: 0, d: 3 },
  { q: "What is the SI unit of force?", a: ["Newton", "Joule", "Pascal", "Watt"], c: 0, d: 3 },
  { q: "Which law relates pressure and volume of a gas at constant temperature?", a: ["Boyle's law", "Ohm's law", "Hooke's law", "Snell's law"], c: 0, d: 3 },
  { q: "Which subatomic particle determines an element's atomic number?", a: ["Proton", "Neutron", "Electron", "Muon"], c: 0, d: 3 },
  { q: "Which branch of mathematics studies rates of change and accumulation?", a: ["Calculus", "Topology only", "Combinatorics", "Number theory"], c: 0, d: 3 },
  { q: "What is the name for the boundary around a black hole beyond which light cannot escape?", a: ["Event horizon", "Photon belt", "Accretion edge", "Gravity shell"], c: 0, d: 3 },
  { q: "Which planet has a day longer than its year?", a: ["Venus", "Mars", "Jupiter", "Neptune"], c: 0, d: 3 },
  { q: "What is the most common isotope of hydrogen?", a: ["Protium", "Deuterium", "Tritium", "Hydronium"], c: 0, d: 3 },
  { q: "Which physicist is associated with the uncertainty principle?", a: ["Werner Heisenberg", "Max Planck", "Erwin Schrödinger", "Enrico Fermi"], c: 0, d: 3 },
  { q: "What is the name for programmed cell death?", a: ["Apoptosis", "Mitosis", "Osmosis", "Meiosis"], c: 0, d: 3 },
  { q: "Which structure connects muscle to bone?", a: ["Tendon", "Ligament", "Cartilage", "Marrow"], c: 0, d: 3 },
  { q: "What is the largest part of the human brain by volume?", a: ["Cerebrum", "Cerebellum", "Medulla", "Pons"], c: 0, d: 3 },
  { q: "Which blood type is commonly called the universal donor for red blood cells?", a: ["O negative", "AB positive", "A positive", "B negative"], c: 0, d: 3 },
  { q: "What is the term for animals active primarily at dawn and dusk?", a: ["Crepuscular", "Nocturnal", "Diurnal", "Arboreal"], c: 0, d: 3 },
  { q: "Which animal has rectangular pupils?", a: ["Goat", "Cat", "Eagle", "Dolphin"], c: 0, d: 3 },
  { q: "What is a group of flamingos commonly called?", a: ["Flamboyance", "Murder", "Parliament", "Crash"], c: 0, d: 3 },
  { q: "Which animal is the only marsupial native to the United States and Canada?", a: ["Virginia opossum", "Wombat", "Wallaby", "Quokka"], c: 0, d: 3 },
  { q: "Which cephalopod has an internal shell called a cuttlebone?", a: ["Cuttlefish", "Octopus", "Nautilus", "Squid only"], c: 0, d: 3 },
  { q: "Which mammal lays eggs and has a duck-like bill?", a: ["Platypus", "Pangolin", "Aardvark", "Tapir"], c: 0, d: 3 },
  { q: "What is the world's largest species of penguin?", a: ["Emperor penguin", "King penguin", "Gentoo penguin", "Adélie penguin"], c: 0, d: 3 },
  { q: "What is the capital of Bhutan?", a: ["Thimphu", "Kathmandu", "Dhaka", "Colombo"], c: 0, d: 3 },
  { q: "Which country has the most natural lakes by number?", a: ["Canada", "Finland", "Russia", "United States"], c: 0, d: 3 },
  { q: "Which strait separates Asia from North America?", a: ["Bering Strait", "Strait of Gibraltar", "Bosporus", "Malacca Strait"], c: 0, d: 3 },
  { q: "What is the capital of Slovenia?", a: ["Ljubljana", "Bratislava", "Zagreb", "Sarajevo"], c: 0, d: 3 },
  { q: "Which desert lies largely in Mongolia and northern China?", a: ["Gobi", "Atacama", "Namib", "Sonoran"], c: 0, d: 3 },
  { q: "Which river flows through Baghdad?", a: ["Tigris", "Euphrates", "Jordan", "Indus"], c: 0, d: 3 },
  { q: "Which country is completely surrounded by South Africa?", a: ["Lesotho", "Eswatini", "Botswana", "Namibia"], c: 0, d: 3 },
  { q: "Which European microstate is located between Switzerland and Austria?", a: ["Liechtenstein", "Andorra", "San Marino", "Monaco"], c: 0, d: 3 },
  { q: "Which capital city stands on the Vltava River?", a: ["Prague", "Warsaw", "Vienna", "Sofia"], c: 0, d: 3 },
  { q: "Which country uses the forint as its currency?", a: ["Hungary", "Romania", "Croatia", "Serbia"], c: 0, d: 3 },
  { q: "Which treaty formally ended World War I between Germany and the Allied powers?", a: ["Treaty of Versailles", "Treaty of Utrecht", "Treaty of Paris 1783", "Treaty of Tordesillas"], c: 0, d: 3 },
  { q: "Which ancient people built the city of Carthage?", a: ["Phoenicians", "Spartans", "Vikings", "Hittites"], c: 0, d: 3 },
  { q: "Who was the first emperor of Rome?", a: ["Augustus", "Nero", "Julius Caesar", "Trajan"], c: 0, d: 3 },
  { q: "Which empire was ruled by Mansa Musa?", a: ["Mali Empire", "Ottoman Empire", "Mughal Empire", "Byzantine Empire"], c: 0, d: 3 },
  { q: "Which city was the capital of the Byzantine Empire for most of its history?", a: ["Constantinople", "Athens", "Alexandria", "Antioch"], c: 0, d: 3 },
  { q: "The Battle of Hastings took place in what year?", a: ["1066", "1215", "1415", "1588"], c: 0, d: 3 },
  { q: "Which explorer's 1492 voyage crossed the Atlantic under the Spanish crown?", a: ["Christopher Columbus", "Vasco da Gama", "James Cook", "Amerigo Vespucci"], c: 0, d: 3 },
  { q: "Which civilization used quipu for record keeping?", a: ["Inca", "Roman", "Maya", "Egyptian"], c: 0, d: 3 },
  { q: "Who wrote The Prince?", a: ["Niccolò Machiavelli", "Thomas More", "Dante Alighieri", "Boccaccio"], c: 0, d: 3 },
  { q: "Which philosopher wrote The Republic?", a: ["Plato", "Aristotle", "Socrates", "Epicurus"], c: 0, d: 3 },
  { q: "Who composed The Four Seasons?", a: ["Antonio Vivaldi", "Johann Sebastian Bach", "Wolfgang Mozart", "Franz Schubert"], c: 0, d: 3 },
  { q: "Which painter is associated with The Persistence of Memory?", a: ["Salvador Dalí", "Henri Matisse", "Edvard Munch", "Paul Cézanne"], c: 0, d: 3 },
  { q: "What is the term for a poem of fourteen lines with a prescribed structure?", a: ["Sonnet", "Haiku", "Limerick", "Ode"], c: 0, d: 3 },
  { q: "Which architectural style is known for pointed arches and flying buttresses?", a: ["Gothic", "Baroque", "Brutalist", "Bauhaus"], c: 0, d: 3 },
  { q: "Which Shakespeare play includes the characters Prospero and Caliban?", a: ["The Tempest", "Twelfth Night", "Julius Caesar", "Richard III"], c: 0, d: 3 },
  { q: "Which novel features the character Jean Valjean?", a: ["Les Misérables", "Madame Bovary", "The Count of Monte Cristo", "Candide"], c: 0, d: 3 },
  { q: "What is the relative minor of C major?", a: ["A minor", "E minor", "D minor", "G minor"], c: 0, d: 3 },
  { q: "In photography, what does aperture directly control?", a: ["Amount of light through the lens", "Battery voltage", "File-name format", "Microphone gain"], c: 0, d: 3 },
  { q: "In typography, what is kerning?", a: ["Adjusting space between specific letter pairs", "Making all letters bold", "Changing page margins", "Adding footnotes"], c: 0, d: 3 },
  { q: "Which word describes a phrase whose initial letters form a pronounceable word?", a: ["Acronym", "Palindrome", "Homophone", "Anagram only"], c: 0, d: 3 },
  { q: "Which data structure follows first-in, first-out order?", a: ["Queue", "Stack", "Tree", "Hash only"], c: 0, d: 3 },
  { q: "In networking, what does DNS primarily translate?", a: ["Domain names to IP addresses", "Images to audio", "Passwords to hashes only", "Wi-Fi to Bluetooth"], c: 0, d: 3 },
  { q: "Which SQL clause is used to filter grouped results after aggregation?", a: ["HAVING", "WHERE only", "ORDER", "JOIN"], c: 0, d: 3 },
  { q: "What is the base-2 number system called?", a: ["Binary", "Decimal", "Hexadecimal", "Octal"], c: 0, d: 3 },
  { q: "Which sorting algorithm repeatedly swaps adjacent out-of-order elements?", a: ["Bubble sort", "Merge sort", "Heap sort", "Radix sort"], c: 0, d: 3 },
  { q: "What does API stand for in software?", a: ["Application Programming Interface", "Automated Process Index", "Advanced Program Internet", "Applied Protocol Integration"], c: 0, d: 3 },
  { q: "What does HTTPS add to HTTP?", a: ["Encrypted transport via TLS", "Faster images only", "Offline storage", "A database engine"], c: 0, d: 3 },
  { q: "Which HTTP status code commonly means 'Not Found'?", a: ["404", "200", "301", "500"], c: 0, d: 3 },
  { q: "What is the culinary term for briefly boiling food and then cooling it quickly?", a: ["Blanching", "Braising", "Deglazing", "Proofing"], c: 0, d: 3 },
  { q: "Which ingredient gives traditional pesto its characteristic nut component?", a: ["Pine nuts", "Peanuts", "Cashews", "Walnuts only"], c: 0, d: 3 },
  { q: "What is the Japanese word commonly used for savory 'fifth taste'?", a: ["Umami", "Sashimi", "Dashi", "Mirin"], c: 0, d: 3 },
  { q: "Which pastry is made by repeatedly folding butter into dough to create layers?", a: ["Puff pastry", "Shortcrust", "Choux", "Cornbread"], c: 0, d: 3 },
  { q: "Which coffee drink traditionally combines espresso with steamed milk and a small cap of foam?", a: ["Cappuccino", "Americano", "Espresso doppio", "Cold brew"], c: 0, d: 3 },
  { q: "Which spice is the dried bark of trees in the genus Cinnamomum?", a: ["Cinnamon", "Nutmeg", "Cardamom", "Anise"], c: 0, d: 3 },
  { q: "What is the term for cooking meat slowly in a small amount of liquid after browning?", a: ["Braising", "Broiling", "Poaching", "Flambéing"], c: 0, d: 3 },
  { q: "What does 'al dente' literally indicate about cooked pasta?", a: ["Firm to the bite", "Covered in cheese", "Cooked in wine", "Served cold"], c: 0, d: 3 },
];
