export const PUNCHLINE_EXTRA_PROMPTS = [
  "The worst possible name for a retirement community: ____.",
  "A warning label that would make a trampoline much more exciting: ____.",
  "The least convincing thing to say while returning a chainsaw: ____.",
  "A rejected slogan for the DMV: ____.",
  "The real reason the neighborhood HOA called an emergency meeting: ____.",
  "The worst thing to hear from the person installing your ceiling fan: ____.",
  "A terrible thing to discover your Roomba has been collecting: ____.",
  "The one phrase that should never be printed on a parachute: ____.",
  "A deeply suspicious item to find in the church lost-and-found: ____.",
  "The strangest thing a dog could bring home from the park: ____.",
  "A new Olympic event that would immediately be banned: ____.",
  "The worst possible theme for a children's birthday party: ____.",
  "A terrible name for a luxury apartment complex: ____.",
  "The least reassuring thing a tattoo artist can say mid-tattoo: ____.",
  "A product that absolutely does not need a subscription plan: ____.",
  "The weirdest thing to receive in a monthly subscription box: ____.",
  "The worst thing to accidentally put through the washing machine: ____.",
  "A new flavor of toothpaste nobody asked for: ____.",
  "The least useful superpower during a bank robbery: ____.",
  "A horrible thing to yell during a surprise party: ____.",
  "The worst possible name for a daycare center: ____.",
  "A suspicious reason your neighbor needs a backhoe at midnight: ____.",
  "The one thing you never want your mechanic to call 'probably fine': ____.",
  "A rejected mascot for a public library: ____.",
  "The least appropriate thing to put on a welcome mat: ____.",
  "A terrible place to hide a spare house key: ____.",
  "The most concerning thing to hear from a babysitter: ____.",
  "A new feature that would ruin elevators forever: ____.",
  "The world's least effective burglar alarm is just ____.",
  "A sign your smart speaker has become too smart: ____.",
  "The worst possible autocorrect replacement for 'I love you': ____.",
  "A terrible notification to receive from your bank at 2 a.m.: ____.",
  "The least useful app to have during a zombie apocalypse: ____.",
  "A software update feature nobody wants: automatic ____.",
  "The weirdest thing to name your Wi-Fi network: ____.",
  "A terrible captcha challenge: Select every square containing ____.",
  "The worst thing your phone could announce at full volume in public: ____.",
  "A suspicious item in your browser history that needs an explanation: ____.",
  "The least secure password imaginable: ____.",
  "A new social network exclusively for people who love ____.",
  "The error message that means your computer has truly given up: ____.",
  "A terrible name for an AI therapist: ____.",
  "The first thing robots will complain about after becoming self-aware: ____.",
  "A smart toilet feature that crosses the line: ____.",
  "The worst possible ringtone during a funeral: ____.",
  "A rejected emoji that would cause international incidents: ____.",
  "The least helpful thing tech support can say: ____.",
  "A video-call background guaranteed to get you fired: ____.",
  "The strangest thing a drone could deliver to your porch: ____.",
  "A terrible name for a cryptocurrency: ____ Coin.",
  "The worst possible opening line for a job interview: ____.",
  "A resume skill that raises more questions than it answers: ____.",
  "The least motivational thing a manager can say on Monday morning: ____.",
  "A meeting title that guarantees nobody will be productive: ____.",
  "A terrible new office holiday tradition: ____.",
  "The item most likely to start a fight in the break room: ____.",
  "A workplace perk that is actually a threat: Free ____.",
  "The worst thing to discover in the office refrigerator: ____.",
  "A suspicious phrase in a company-wide email: 'Effective immediately, ____.'",
  "The least professional Zoom display name: ____.",
  "A terrible corporate retreat destination: ____.",
  "The worst team-building exercise involving only duct tape and ____.",
  "A rejected corporate value: Radical ____.",
  "The worst thing your boss could say while holding a shovel: ____.",
  "An office supply nobody should need in bulk: ____.",
  "The least inspiring award at the company banquet: ____ of the Year.",
  "The real reason the copier is always jammed: ____.",
  "A terrible out-of-office message: 'I will return when ____.'",
  "The worst thing to hear while your plane is taxiing: ____.",
  "A suspicious amenity at a two-star motel: Complimentary ____.",
  "The least relaxing activity at a spa: ____.",
  "The worst possible cruise-ship theme night: ____ Night.",
  "A terrible souvenir from a national park: ____.",
  "The one thing you do not want your tour guide to whisper: ____.",
  "The worst reason for a flight delay: ____.",
  "A new airline fee that finally breaks society: $25 for ____.",
  "The strangest thing to find in the seat-back pocket on an airplane: ____.",
  "A terrible name for a roadside motel: The ____ Inn.",
  "The least reassuring sign at a water park: ____.",
  "The worst possible phrase on a rental-car agreement: ____ not included.",
  "A vacation photo that absolutely should not be your holiday card: ____.",
  "The world's saddest amusement-park ride: ____ Mountain.",
  "The worst thing to hear while strapped into a roller coaster: ____.",
  "A terrible attraction for a theme park called 'Budget Kingdom': ____.",
  "The snack nobody wants sold at a public swimming pool: ____.",
  "The least romantic item on a room-service menu: ____ for two.",
  "A terrible excuse for missing the hotel checkout time: ____.",
  "The worst possible name for a seafood restaurant: ____.",
  "A suspicious new flavor at an ice cream shop: ____ Surprise.",
  "The ingredient that would instantly ruin a wedding cake: ____.",
  "A terrible thing for a chef to yell from the kitchen: ____.",
  "The least appetizing food to serve in a champagne flute: ____.",
  "A new food trend that must be stopped immediately: ____ toast.",
  "The worst possible filling for a doughnut: ____.",
  "A rejected menu item at a fancy steakhouse: ____ à la mode.",
  "A terrible cereal prize: Free ____ inside.",
  "The one condiment that should never come in a gallon jug: ____.",
  "A cooking instruction that should make you abandon the recipe: 'Now add ____.'",
  "The least convincing name for a diet plan: The ____ Method.",
  "A terrible slogan for a buffet: 'Come hungry. Leave ____.'",
  "The worst thing to discover floating in your soup: ____.",
  "A suspiciously specific warning on a hot sauce bottle: Do not use near ____.",
  "The strangest thing to put on a charcuterie board: ____.",
  "A terrible food to eat while wearing white: ____.",
  "The least romantic thing to say during a candlelit dinner: ____.",
  "A terrible first-date activity: competitive ____.",
  "The one question guaranteed to make Thanksgiving dinner awkward: ____?",
  "A bad thing to engrave inside a wedding ring: ____.",
  "The least reassuring text from a new romantic partner: ____.",
  "A terrible reason to break up with someone by PowerPoint: Slide 4: ____.",
  "The worst gift to give on a first anniversary: ____.",
  "A dating profile that begins 'Ask me about my ____' is already in trouble.",
  "The strangest thing to bring when meeting your partner's parents: ____.",
  "The least romantic place to propose marriage: ____.",
  "A terrible couples nickname: The ____ Twins.",
  "The one phrase nobody wants to hear during family game night: ____.",
  "A suspicious family tradition involving a locked basement and ____.",
  "The worst secret to reveal in a wedding toast: ____.",
  "A terrible thing to accidentally call your mother-in-law: ____.",
  "The least appropriate inscription on a baby shower cake: ____.",
  "A new reality show about families competing to ____.",
  "The worst thing to find in an old family photo album: ____.",
  "A rejected name for a family group chat: ____.",
  "The real reason grandma keeps a baseball bat behind the couch: ____.",
  "The least comforting thing a ghost can say: ____.",
  "A haunted object nobody would bother exorcising: ____.",
  "The worst thing to find written in your attic dust: ____.",
  "A terrible name for a ghost-hunting podcast: ____.",
  "The monster in the closet is embarrassed because it secretly loves ____.",
  "A vampire's least impressive weakness: ____.",
  "The one item a werewolf should never order online: ____.",
  "A terrible sentence to hear from a Ouija board: ____.",
  "The weirdest thing a witch could keep in her freezer: ____.",
  "A zombie's most annoying personality trait: ____.",
  "The least scary phrase carved into an ancient tomb: ____.",
  "A horror movie that would end in five minutes if everyone just ____.",
  "The ghost's unfinished business turns out to be ____.",
  "A terrible name for an evil doll: ____.",
  "The worst thing a fortune teller could say after looking at your palm: ____.",
  "A suspicious reason a cemetery needs free Wi-Fi: ____.",
  "The least useful weapon against a monster: ____.",
  "The real reason aliens refuse to visit Earth: ____.",
  "The first law passed after cats take over the government: ____.",
  "A terrible thing to find at the end of a rainbow: ____.",
  "The moon has been replaced by ____ and nobody noticed.",
  "The worst possible side effect of time travel: ____.",
  "A rejected superhero name: Captain ____.",
  "The least impressive magical spell: Expelli-____!",
  "A terrible thing for your clone to say the first time you meet: ____.",
  "The one thing dragons are actually afraid of: ____.",
  "A suspicious new constellation named The ____.",
  "The worst wish to make with a genie: ____.",
  "The first product sold in a store on Mars: ____.",
  "A terrible job for a centaur: ____.",
  "The secret password to enter the wizard council is somehow ____.",
  "The least heroic thing to shout before charging into battle: ____.",
  "A bad name for a spaceship: The USS ____.",
  "The strangest thing found during the first expedition to another galaxy: ____.",
  "A terrible prophecy: 'When the red moon rises, ____.'",
  "The one thing mermaids absolutely hate about the ocean: ____.",
  "A rejected national holiday celebrating ____.",
  "The worst thing to put on a town welcome sign: Population 842 and ____.",
  "A new law that would immediately cause chaos: Everyone must ____ on Tuesdays.",
  "The least qualified person to be mayor: ____.",
  "A terrible thing to announce over a grocery-store loudspeaker: ____.",
  "The weirdest item available at a government surplus auction: ____.",
  "The worst possible thing to name a hurricane: ____.",
  "A suspicious reason the local news helicopter is following you: ____.",
  "The least helpful emergency alert: 'Remain indoors because ____.'",
  "A terrible town motto: 'Come for the ____. Stay because you have to.'",
  "The worst thing to discover underneath city hall: ____.",
  "A strange reason your mail carrier refuses to approach your house: ____.",
  "A terrible use for a public fountain: ____.",
  "The least appropriate parade float: ____.",
  "The real reason the library closes early every Thursday: ____.",
  "The town's new mascot is just a person dressed as ____.",
  "A suspicious thing to hear over a police scanner: 'Subject is carrying ____.'",
  "The least impressive Guinness-style world record: Most ____ in one minute.",
  "The worst thing to have fall out of your pocket at airport security: ____.",
  "A terrible item to inherit from a distant relative: ____.",
  "The weirdest thing to accidentally buy at an estate sale: ____.",
  "The least useful advice from a survival expert: ____.",
  "A new extreme sport involving ____ and a leaf blower.",
  "The worst possible thing to collect as a hobby: ____.",
  "A terrible phrase to put on a motivational coffee mug: ____.",
  "The strangest thing to whisper before blowing out birthday candles: ____.",
  "A bad reason to become famous: ____.",
  "The least impressive secret identity: By day, ____.",
];

export const PUNCHLINE_EXTRA_SPICY_PROMPTS = [
  "The worst thing to whisper after saying 'I booked us a romantic weekend': ____.",
  "A terrible thing to find under the bed on a first overnight date: ____.",
  "The least sexy phrase involving the words 'insurance deductible': ____.",
  "A dating-app message that should trigger an automatic background check: ____.",
  "The worst possible couples tattoo: ____.",
  "A terrible nickname to use during an argument: ____.",
  "The one phrase that instantly ruins a candlelit bedroom: ____.",
  "A suspicious thing to keep in a nightstand labeled 'emergencies only': ____.",
  "The least romantic reason to buy a king-size bed: ____.",
  "The worst thing to hear through the hotel wall on your honeymoon: ____.",
  "A terrible safe word for a relationship: ____.",
  "The least seductive way to say 'come over': ____.",
  "A dating profile red flag disguised as a hobby: ____.",
  "The weirdest thing to have delivered to a romantic dinner: ____.",
  "A terrible text to send immediately after a first kiss: ____.",
  "The worst possible romantic playlist title: ____.",
  "A suspicious reason your date has brought a tarp: ____.",
  "The least reassuring thing to hear while someone locks the bedroom door: ____.",
  "A terrible thing to write in an anniversary card: ____.",
  "The phrase guaranteed to make a hot-tub conversation weird: ____.",
  "A romantic gift that definitely came from a gas station: ____.",
  "The worst possible theme for an adults-only resort: ____.",
  "The least flattering compliment after someone takes off their clothes: ____.",
  "A terrible pickup line involving a Costco membership: ____.",
  "The one item you should never bring to couples counseling: ____.",
  "The strangest thing to yell while sneaking out of someone's house: ____.",
  "A terrible answer to 'What are your intentions with my daughter/son?': ____.",
  "The least romantic thing to say while sharing a shower: ____.",
  "The worst thing to accidentally AirDrop to everyone at a wedding: ____.",
  "A suspicious charge to see on a shared credit-card bill: ____.",
  "The phrase that should never be printed on lingerie: ____.",
  "The worst possible name for a romantic candle scent: ____.",
  "A terrible reason to keep handcuffs in the kitchen: ____.",
  "The least sexy item to wear with nothing else: ____.",
  "A dating coach's worst possible advice: ____.",
  "The strangest sentence to include in wedding vows: 'I promise to always ____.'",
  "A terrible thing for a partner to say after looking through your phone: ____.",
  "The worst place to discover glitter after a business trip: ____.",
  "The least believable reason for owning twelve bottles of massage oil: ____.",
  "A terrible romantic surprise involving a leaf blower and ____.",
  "The phrase most likely to end a make-out session instantly: ____.",
  "A suspicious password for a locked folder on your partner's laptop: ____.",
  "The least appropriate thing to shout from a hotel balcony at 3 a.m.: ____.",
  "A terrible answer when your partner asks 'Who is that?': ____.",
  "The weirdest thing to add to a dating-app list of 'must-haves': ____.",
  "The worst possible bachelor/bachelorette party souvenir: ____.",
  "A terrible thing to reveal during a romantic game of Truth or Dare: ____.",
  "The least sexy way to ask for consent to borrow a phone charger: ____.",
  "A suspicious thing for a motel desk clerk to say while handing you the key: ____.",
  "The worst romantic advice your drunk uncle could give: ____.",
  "A terrible phrase to hear from someone wearing only one sock: ____.",
  "The strangest reason to buy a second mattress: ____.",
  "A bad thing to discover has been livestreamed: ____.",
  "The least romantic use for rose petals: ____.",
  "A terrible thing to name a shared couples calendar event: ____.",
  "The worst possible autocorrect during sexting: ____.",
  "A suspicious excuse for disappearing into the bathroom with a Bluetooth speaker: ____.",
  "The least reassuring response to 'Have you done this before?': ____.",
  "A terrible romantic slogan for a mattress store: ____.",
  "The strangest thing to have monogrammed for your partner: ____.",
];
