import React,{useMemo,useState} from "react";
import {BOARD_SIZE,CORRIDOR_SPACES,LOCATIONS,boardRoomId,getReachableBoardNodes,normalizeBoardPosition,roomNodeId} from "./engineV3.js";
import {ROOM_SCENE_ASSETS,spriteStyle} from "./sceneAssets.js";

const LOCATION_MAP=Object.freeze(Object.fromEntries(LOCATIONS.map(x=>[x.id,x])));
const ROOM_META={greenhouse:["🌿","Climate sensors · smart glass"],penthouse:["🏙","Biometric safe · smart glass"],security:["📹","CCTV wall · badge logs"],laundry:["🫧","RFID linen tracking"],atrium:["◉","Building controls · elevators"],kitchen:["🍽","Cold-chain sensors · service cams"],garage:["🚘","ANPR cameras · EV chargers"],nightclub:["♬","DMX lighting · audio console"],boiler:["♨","BMS telemetry · pressure sensors"]};
function Pawn({member,you}){const hue=(Number(member.seat||0)*61+8)%360;return <span className={`b3-pawn ${you?"you":""}`} style={{"--h":hue}} title={member.nickname}><i/><b>{member.avatar||"●"}</b></span>}
function Passages({roomId}){return <svg className="b3-passages" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path className={roomId==="greenhouse"||roomId==="boiler"?"active":""} d="M13 10 C -4 42,18 96,88 88"/><path className={roomId==="security"||roomId==="garage"?"active":""} d="M90 9 C 104 39,84 92,13 84"/></svg>}

export default function BlackglassBoard({state,members,user,myTurn,busy,act}){
 const me=members.find(m=>m.uid===user?.uid),myNode=normalizeBoardPosition(state.positions?.[user?.uid],me?.seat),myRoom=boardRoomId(myNode);const [intel,setIntel]=useState(false),[zoom,setZoom]=useState(1);
 const reachable=useMemo(()=>myTurn&&state.turnPhase==="move"&&user?.uid?new Map(getReachableBoardNodes(state,user.uid,members).map(x=>[x.id,x])):new Map(),[state,members,myTurn,user?.uid]);
 const doors=useMemo(()=>new Set(LOCATIONS.flatMap(r=>r.doors.map(({x,y})=>`hall:${x},${y}`))),[]);
 const occupants=id=>members.filter(m=>normalizeBoardPosition(state.positions?.[m.uid],m.seat)===id);const move=id=>reachable.has(id)&&!busy&&act({type:"move",nodeId:id});
 return <section className={`b3-board-shell ${intel?"intel":""}`} data-testid="blackglass-board"><header><div><small>INVESTIGATION FLOOR</small><strong>{myRoom?LOCATION_MAP[myRoom]?.name:"Hotel corridor"}</strong></div><nav><button type="button" onClick={()=>setIntel(v=>!v)} className={intel?"active":""}>⌁ Intel</button><button type="button" aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.85,v-.08))}>−</button><button type="button" onClick={()=>setZoom(1)}>Fit</button><button type="button" aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(1.2,v+.08))}>＋</button></nav></header><div className="b3-board-viewport"><div className="b3-board" style={{"--zoom":zoom}}><Passages roomId={myRoom}/>{LOCATIONS.map(room=>{const b=room.bounds,id=roomNodeId(room.id),reach=reachable.get(id),here=myNode===id,[icon,tech]=ROOM_META[room.id],people=occupants(id),style={left:`${b.x/BOARD_SIZE*100}%`,top:`${b.y/BOARD_SIZE*100}%`,width:`${b.w/BOARD_SIZE*100}%`,height:`${b.h/BOARD_SIZE*100}%`};return <button key={room.id} type="button" className={`b3-room theme-${room.theme} ${reach?"reachable":""} ${here?"here":""}`} style={style} disabled={!reach||busy} onClick={()=>move(id)} aria-label={reach?`Enter ${room.name}, costs ${reach.distance} movement`:room.name}><span className="b3-room-photo" style={spriteStyle(ROOM_SCENE_ASSETS[room.id])}/><span className="b3-room-shade"/><span className="b3-room-copy"><small>{here?"YOU ARE HERE":reach?`${reach.distance} MOVE${reach.distance===1?"":"S"}`:"CRIME SCENE"}</small><strong>{room.name}</strong></span><span className="b3-room-tech">{icon} {tech}</span>{room.passageTo?<span className="b3-passage-chip">SECRET ↝ {LOCATION_MAP[room.passageTo]?.name}</span>:null}{people.length?<span className="b3-room-pawns">{people.map(m=><Pawn key={m.uid} member={m} you={m.uid===user?.uid}/>)}</span>:null}</button>})}{CORRIDOR_SPACES.map(space=>{const reach=reachable.get(space.id),here=myNode===space.id,people=occupants(space.id),left=(space.x+.5)/BOARD_SIZE*100,top=(space.y+.5)/BOARD_SIZE*100;return <button key={space.id} type="button" className={`b3-hall ${doors.has(space.id)?"door":""} ${reach?"reachable":""} ${here?"here":""}`} style={{left:`${left}%`,top:`${top}%`}} disabled={!reach||busy} onClick={()=>move(space.id)} aria-label={reach?`Move ${reach.distance} spaces here`:doors.has(space.id)?"Hotel door":"Hotel corridor"}>{reach?<span>{reach.distance}</span>:doors.has(space.id)?<span>▣</span>:null}{people.length?<span className="b3-hall-pawns">{people.map(m=><Pawn key={m.uid} member={m} you={m.uid===user?.uid}/>)}</span>:null}</button>})}</div></div><footer><span><i className="walk"/> {CORRIDOR_SPACES.length} walk spaces</span><span><i className="door"/> Doors</span><span><i className="secret"/> Secret passages</span><span>⌁ Intel reveals hotel tech</span></footer></section>;
}
