import React,{useEffect,useRef,useState} from "react";
import {LOCATIONS,METHODS,SUSPECTS,evidenceLabel} from "./engineV3.js";
import {RECONSTRUCTION_COMBINATION_COUNT,reconstructionAssetSet} from "./sceneAssets.js";
import {CRIME_SCENE_PIPELINE_VERSION,renderCrimeScene} from "./crimeScenePipeline.js";
const LOC=Object.freeze(Object.fromEntries(LOCATIONS.map(x=>[x.id,x]))),SUS=Object.freeze(Object.fromEntries(SUSPECTS.map(x=>[x.id,x]))),MET=Object.freeze(Object.fromEntries(METHODS.map(x=>[x.id,x])));const VICTIM={name:"Ruby Ash",role:"investigative journalist"};
export default function BlackglassReconstruction({scenario,refuter,shown,onClose}){
 const canvasRef=useRef(null),[status,setStatus]=useState("rendering"),[renderError,setRenderError]=useState("");
 const room=scenario?LOC[scenario.locationId]:null,suspect=scenario?SUS[scenario.suspectId]:null,method=scenario?MET[scenario.methodId]:null,a=scenario?reconstructionAssetSet(scenario.suspectId,scenario.methodId,scenario.locationId):null;
 useEffect(()=>{if(!scenario||!canvasRef.current)return;let active=true;setStatus("rendering");setRenderError("");renderCrimeScene(canvasRef.current,scenario,{room:room?.name||scenario.locationId,suspect:suspect?.name||scenario.suspectId,method:method?.name||scenario.methodId}).then(()=>{if(active)setStatus("ready")}).catch(error=>{if(active){setStatus("error");setRenderError(error?.message||"Unable to render reconstruction.")}});return()=>{active=false}},[scenario?.suspectId,scenario?.methodId,scenario?.locationId,scenario?.turn,room?.name,suspect?.name,method?.name]);
 if(!scenario)return null;
 return <div className="b3-recon-backdrop" role="dialog" aria-modal="true" aria-label="Theory reconstruction"><article className={`b3-recon method-${scenario.methodId} ${status}`} data-testid="blackglass-scenario-modal" data-canonical-suspect={a.suspect.canonicalId} data-canonical-victim={a.victim.canonicalId} data-pipeline={CRIME_SCENE_PIPELINE_VERSION}><button type="button" className="b3-recon-close" onClick={onClose} aria-label="Close reconstruction">×</button><header><small>FORENSIC RECONSTRUCTION · THEORY {scenario.turn}</small><h2>{suspect.name} · {method.name}</h2><p>{room.name} · victim: {VICTIM.name} · identity-locked scene {scenario.suspectId}/{scenario.methodId}/{scenario.locationId}</p></header><div className="b3-cinematic-frame"><canvas ref={canvasRef} className="b3-crime-scene-canvas" data-testid="blackglass-crime-scene" aria-label={`${suspect.name} with ${method.name} in ${room.name}, victim ${VICTIM.name}`}/>{status==="rendering"?<div className="b3-scene-loading"><span/><strong>Reconstructing the scene…</strong></div>:null}{status==="error"?<div className="b3-scene-error"><strong>Scene renderer failed</strong><span>{renderError}</span></div>:null}<div className="b3-scene-caption"><span><b>Suspect</b>{suspect.name}</span><span><b>Method</b>{method.name}</span><span><b>Scene</b>{room.name}</span><span><b>Victim</b>{VICTIM.name}</span></div></div><footer className={refuter?"refuted":"unresolved"}><div><small>{refuter?"THE THEORY WAS REFUTED":"NO REFUTATION YET"}</small><strong>{refuter?`${refuter.nickname} produced evidence.`:"Nobody at the table could refute this reconstruction."}</strong>{shown?<span>Privately shown: {evidenceLabel(shown)}</span>:<span>{RECONSTRUCTION_COMBINATION_COUNT} possible identity-locked reconstructions.</span>}</div><button type="button" onClick={onClose}>Continue investigation</button></footer></article></div>}
