export const GAME_CATEGORIES = [
  {
    id: "card",
    label: "Card Games",
    icon: "🂡",
    description: "Classic hands, tricks, melds, draws, slaps, and family-table chaos.",
  },
  {
    id: "board",
    label: "Board Games",
    icon: "♟",
    description: "Strategy, deduction, wordplay, property battles, and head-to-head tabletop games.",
  },
  {
    id: "video",
    label: "Video Games",
    icon: "🎮",
    description: "Digital-first adventures, party shows, and phone-controlled experiences.",
  },
  {
    id: "arcade",
    label: "Arcade Games",
    icon: "🕹️",
    description: "Classic coin-op play with browser emulation and legally obtained ROMs.",
  },
];

export const GAME_CATALOG = [
  { id: "canasta", category: "card", name: "Canasta", icon: "♣", eyebrow: "Meld strategy", description: "The complete family Canasta table, preserved exactly as it plays today.", players: "2–6 players", status: "Ready" },
  { id: "pixelquest", category: "video", name: "PixelQuest: The Living Dungeon", icon: "⚔", eyebrow: "Co-op fantasy campaign", description: "A 1–8 player living dungeon with honest d20 dice, tactical battles, party votes, private choices, AI companions, and twenty adventure cartridges.", players: "1–8 online players", status: "Ready" },
  { id: "punchline", category: "video", name: "Punchline", icon: "🎤", eyebrow: "Write it · vote it", description: "A big-screen comedy show where every phone writes the punchlines and the room decides what lands.", players: "3–12 phones", status: "Ready" },
  { id: "lastonealive", category: "video", name: "Last One Alive", icon: "👻", eyebrow: "Trivia · traps · escape", description: "Horror-comedy trivia with six survival micro-games, ghosts, resurrection, and a final race for the exit.", players: "3–12 phones", status: "Ready" },
  { id: "doodlealibi", category: "video", name: "Doodle Alibi", icon: "🖍️", eyebrow: "Draw · accuse · deceive", description: "Draw secret assignments on your phone, study the TV evidence wall, and expose the altered prompt.", players: "4–12 phones", status: "Ready" },
  { id: "arcade", category: "arcade", name: "Browser Arcade", icon: "🕹️", eyebrow: "80s & 90s coin-op classics", description: "A browser arcade cabinet with MAME 2003 emulation, a FinalBurn Neo fallback, local ROM loading, and a curated list of rights-approved free ROM sources.", players: "1–2 local players", status: "Ready" },
  { id: "slumlord", category: "board", name: "Slum Lord", icon: "🏚️", eyebrow: "Buy · patch · collect", description: "A full-board property game with terrible maintenance: buy the block, patch the leaks, dodge inspections, trade properties, and collect rent.", players: "2–4 local players", status: "Ready" },
  { id: "chess", category: "board", name: "Chess", icon: "♚", eyebrow: "Pure strategy", description: "Full legal chess with check, checkmate, castling, en passant, stalemate, and a quick robot opponent.", players: "2 players", status: "Ready" },
  { id: "checkers", category: "board", name: "Checkers", icon: "⛀", eyebrow: "Jump · crown · trap", description: "American checkers with mandatory captures, chained jumps, kings, online rooms, and robot play.", players: "2 players", status: "Ready" },
  { id: "lexiconforge", category: "board", name: "Lexicon Forge", icon: "⚒", eyebrow: "Build words · claim premiums", description: "Original word-tile strategy with seven-tile racks, cross-word scoring, exchanges, custom tile math, and house-rule word challenges.", players: "2–4 players", status: "Ready" },
  { id: "bloodalibi", category: "board", name: "Blackglass: Blood & Alibi", icon: "🩸", eyebrow: "Modern murder mystery", description: "A darker deduction case with six original suspects, nine crime scenes, brutal methods, evidence files, and final accusations.", players: "2–6 investigators", status: "Ready" },
  { id: "hearts", category: "card", name: "Hearts", icon: "♥", eyebrow: "Avoid the points", description: "Pass three cards, dodge penalty tricks, and try to shoot the moon.", players: "4 players", status: "Planned" },
  { id: "spades", category: "card", name: "Spades", icon: "♠", eyebrow: "Bid with a partner", description: "Call your contract, manage bags, protect nil bids, and race to 500.", players: "4 players", status: "Planned" },
  { id: "rummy", category: "card", name: "Rummy", icon: "♦", eyebrow: "Sets and runs", description: "Draw, meld, lay off, and be the first player to empty your hand.", players: "2–6 players", status: "Planned" },
  { id: "gofish", category: "card", name: "Go Fish", icon: "🐟", eyebrow: "Ask, draw, collect", description: "Ask for ranks you hold, build four-card books, and fish from the pond when you miss.", players: "2–6 players", status: "Planned" },
  { id: "connect4", category: "board", name: "Connect 4", icon: "🔴", eyebrow: "Vertical strategy", description: "Drop checkers into a 7×6 board, block threats, and connect four before your opponent.", players: "2 players", status: "Planned" },
  { id: "battleship", category: "board", name: "Battleship", icon: "⚓", eyebrow: "Hidden-fleet tactics", description: "Hunt a hidden 10×10 fleet with classic ships, alternating shots, hits, misses, and sinks.", players: "2 players", status: "Planned" },
  { id: "hnefatafl", category: "board", name: "Hnefatafl", icon: "♔", eyebrow: "Viking king hunt", description: "An asymmetric 11×11 siege: raiders hunt the king while defenders fight to escape him to a corner.", players: "2 players", status: "Planned" },
  { id: "ers", category: "card", name: "Egyptian Rat Screw", icon: "⚡", eyebrow: "Flip and react", description: "Survive face-card challenges and be first to slap doubles, sandwiches, tens, and more.", players: "2–6 players", status: "Planned" },
  { id: "spoons", category: "card", name: "Spoons", icon: "🥄", eyebrow: "Four of a kind scramble", description: "Pass fast, collect four of a kind, then grab a spoon before somebody else does.", players: "3–6 players", status: "Planned" },
  { id: "indians", category: "card", name: "Indians", icon: "♠", eyebrow: "Progressive Spades", description: "Play partnership Spades while another complete low rank disappears every hand.", players: "4 players", status: "Planned" },
  { id: "poker", category: "card", name: "Five-Card Draw", icon: "★", eyebrow: "Family poker points", description: "Classic draw poker with game points only: bet, draw, bluff, and compare hands.", players: "2–6 players", status: "Planned" },
  { id: "golf", category: "card", name: "Six Card Golf", icon: "⛳", eyebrow: "Low score wins", description: "Improve a six-card grid across nine holes and cancel matching columns to zero.", players: "2–4 players", status: "Planned" },
  { id: "chompageddon", category: "video", name: "Chompageddon!", icon: "👹", eyebrow: "Physics party arcade", description: "Outrageous monsters lunge into a shared bouncing ball pit. Play solo, cause couch chaos, or battle friends online with room codes and bots filling empty seats.", players: "1–4 local · 2–4 online", status: "Planned" },
  { id: "gofyourself", category: "card", name: "Go F' Yourself", icon: "😈", eyebrow: "Go Fish after dark · 18+", description: "Go Fish with profanity, raunchy innuendo, toxic exes, bad decisions, and absolutely no dignity.", players: "2–6 adults", status: "Planned" },
];
